### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by Micalhl** [DreamVoid/MiraiMC#1]
我看你的 MiraiBot 类必须传入一个继承 JavaPlugin 的 BukkitPlugin 类才可以工作
但是我的插件是用 TabooLib 写的呀, 插件主类是 io.izzel.taboolib.loader.Plugin
所以没有办法用你的方法去构造登陆一个机器人
所以希望可以优化一下 API

**Comment by DreamVoid** [comment]
设计的时候只想着让插件的其他方法调用了，没想到这回事，马上修复。

**Comment by DreamVoid** [comment]
已修复，请使用[1.1-rc2](https://github.com/DreamVoid/MiraiMC/releases/tag/v1.1-rc2)

**Comment by Micalhl** [comment]
好的好的，谢了。
其实我才发现 BukkitPlugin 是你的插件主类（
