### ISSUE TITLE
MiraiMC 1.6 无法在低版本服务端加载

### ISSUE THREAD

**Issue by chettestwef** [DreamVoid/MiraiMC#114]
### 问题描述

正常将插件放入plugins文件夹并启动服务器
输入MiraiMC没有此命令

### 复现方法

1. 正常将插件放入plugins文件夹并启动服务器
2. 输入MiraiMC没有此命令

### 服务端类型

Bukkit（包括Paper）

### 服务端版本

PaperSpigot-f6fba00-9935adc (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### MiraiMC 插件版本

1.6

### 服务端日志

```text
见额外说明
```

### 额外说明

[2022-02-09-1.log](https://github.com/DreamVoid/MiraiMC/files/8030578/2022-02-09-1.log)

**Comment by chettestwef** [comment]
[latest (21).log](https://github.com/DreamVoid/MiraiMC/files/8012781/latest.21.log)

**Comment by chettestwef** [comment]
抱歉，不小心点到关闭了

**Comment by DreamVoid** [comment]
` [MiraiMC] Loading MiraiMC v1.5.3`
？

**Comment by chettestwef** [comment]
我更新了，现在的版本是 This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
下载的是https://github.com/DreamVoid/MiraiMC/issues/86内的链接https://papermc.io/api/v2/projects/paper/versions/1.8.8/builds/445/downloads/paper-1.8.8-445.jar
现在是输入后没有反应
![image](https://user-images.githubusercontent.com/99162086/152817989-dccfae65-d2fb-41ef-b7f8-9b62c82e468d.png)
以下是服务端日志
[latest (22).log](https://github.com/DreamVoid/MiraiMC/files/8016491/latest.22.log)
不知道在这给您回复您看不看得见，如果看见的话回复一下，麻烦了

**Comment by chettestwef** [comment]
Jdk 8 环境 (1.7.10 - 1.12.2 Java)
我现在发工单申请换到JAVA11

**Comment by DreamVoid** [comment]
一些面板服务器提供商可能提供的不是通常使用的Java 8。如果确实是这样，那么对于这类情况，我可能无法进行修复（未来可能通过改良插件工作方式间接修复）

**Comment by chettestwef** [comment]
抱歉，我在其更换了JDK运行版本后（11-17）还是运行指令无输出
![image](https://user-images.githubusercontent.com/99162086/153141469-b9dd0746-cb55-4079-8f86-a1752d91ac44.png)
请稍等，我在本地试试，或者换个版本

**Comment by chettestwef** [comment]
您好，本地测试过了，运行指令无输出
JAVA版本：
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)
本地运行截图：
![image](https://user-images.githubusercontent.com/99162086/153142365-288d1956-8120-4c85-99cd-caf8a12873d2.png)
本地运行日志：
[latest.log](https://github.com/DreamVoid/MiraiMC/files/8030398/latest.log)
我现在尝试MiraiMC1.5.3版本

**Comment by chettestwef** [comment]
抱歉久等了！目前的版本为：MiraiMC1.5.3正式版
样本(因为github不能上传后缀名为.jar的文件，所以我打包了,请见谅)：[MiraiMC-Bukkit (2).zip](https://github.com/DreamVoid/MiraiMC/files/8030458/MiraiMC-Bukkit.2.zip)
miraimc1.5.3成功加载！
![image](https://user-images.githubusercontent.com/99162086/153144248-33d732f0-b27c-4ee6-8a94-f9df2b671a10.png)


[latest.log](https://github.com/DreamVoid/MiraiMC/files/8030500/latest.log)
版本MiraiMC：1.5.3
JAVA版本：
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)
成功加载

**Comment by chettestwef** [comment]
补图
![image](https://user-images.githubusercontent.com/99162086/153144608-198faf1d-8cdf-4f32-8eb9-46441aa000f8.png)

**Comment by chettestwef** [comment]
**MiraiMC-1.5.3登陆报错**
**运行环境：**
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)
windows 10 x64 21h1
**核心:**paperspigot1.8.8
**版本:**
git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
**报错日志**
[latest.log](https://github.com/DreamVoid/MiraiMC/files/8030545/latest.log)

**Comment by chettestwef** [comment]
**总结，我测试了以下版本:**MiraiMC-Bukkit 1.6，MiraiMC-Bukkit 1.5.3
**运行环境:**
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)
**测试环境均为本地测试**:Microsoft Windows 10 x64专业版 10.0.19044 内部版本 19044
**服务端版本:**
This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
**MiraiMC-Bukkit 1.6无法加载(以下为运行日志)**
[2022-02-09-1.log](https://github.com/DreamVoid/MiraiMC/files/8030578/2022-02-09-1.log)
**MiraiMC-Bukkit 1.5.3成功加载，但在登录时报错(以下为运行日志)**
[latest.log](https://github.com/DreamVoid/MiraiMC/files/8030599/latest.log)

**Comment by DreamVoid** [comment]
> **总结，我测试了以下版本:**MiraiMC-Bukkit 1.6，MiraiMC-Bukkit 1.5.3 **运行环境:** java version "1.8.0_311" Java(TM) SE Runtime Environment (build 1.8.0_311-b11) Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode) **测试环境均为本地测试**:Microsoft Windows 10 x64专业版 10.0.19044 内部版本 19044 **服务端版本:** This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) **MiraiMC-Bukkit 1.6无法加载(以下为运行日志)** [2022-02-09-1.log](https://github.com/DreamVoid/MiraiMC/files/8030578/2022-02-09-1.log) **MiraiMC-Bukkit 1.5.3成功加载，但在登录时报错(以下为运行日志)** [latest.log](https://github.com/DreamVoid/MiraiMC/files/8030599/latest.log)

已确认1.6在低版本服务端存在的加载问题。
1.5.3版本无法登录是你的服务端有阻止网络连接的行为，可能是代码或者Java内部造成的。

**Comment by chettestwef** [comment]
> > > **总结，我测试了以下版本:**MiraiMC-Bukkit 1.6，MiraiMC-Bukkit 1.5.3 **运行环境:** java version "1.8.0_311" Java(TM) SE Runtime Environment (build 1.8.0_311-b11) Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode) **测试环境均为本地测试**:Microsoft Windows 10 x64专业版 10.0.19044 内部版本 19044 **服务端版本:** This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) **MiraiMC-Bukkit 1.6无法加载(以下为运行日志)** [2022-02-09-1.log](https://github.com/DreamVoid/MiraiMC/files/8030578/2022-02-09-1.log) **MiraiMC-Bukkit 1.5.3成功加载，但在登录时报错(以下为运行日志)** [latest.log](https://github.com/DreamVoid/MiraiMC/files/8030599/latest.log)
> > 
> > 
> > 已确认1.6在低版本服务端存在的加载问题，将会在1.6.1或1.7版本修复。
> > ```
> > [15:24:22] [Server thread/ERROR]: Class com.google.common.base.Suppliers$MemoizingSupplier does not implement the requested interface java.util.function.Supplier initializing MiraiMC v1.6 (Is it up to date?)
> > java.lang.IncompatibleClassChangeError: Class com.google.common.base.Suppliers$MemoizingSupplier does not implement the requested interface java.util.function.Supplier
> > 	at me.dreamvoid.miraimc.internal.MiraiLoader.loadLibraryClass(MiraiLoader.java:125) ~[?:?]
> > 	at me.dreamvoid.miraimc.internal.MiraiLoader.loadMiraiCore(MiraiLoader.java:28) ~[?:?]
> > 	at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onLoad(BukkitPlugin.java:29) ~[?:?]
> > 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:298) [patched_1.8.8.jar:git-PaperSpigot-445]
> > 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched_1.8.8.jar:git-PaperSpigot-445]
> > 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
> > 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 1.5.3版本无法登录是你的服务端有阻止网络连接的行为，可能是代码或者Java内部造成的。
> > 下次反馈类似问题的时候，我回复之前需要补充相关内容，可以编辑原有评论，不要一直发新的评论。要不然看着很难受，拖慢效率。而且你如果在一开始就把问题描述清楚而不是标1.6却用1.5.3的日志，我很快就能找到问题所在。
> 
> **抱歉，我的操作有点生疏，在上传日志时，我不小心上传了错误的日志，抱歉了，我在使用1.5.3版本时候使用了2个版本的核心进行测试，以下是我的测试结果** 插件成功加载，但在登录时无反应，长时间等待后报错。 **服务端版本:**git-PaperSpigot-f6fba00-9935adc (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) **MiraiMC版本:**1.5.3 **以下为报错截图** ![image](https://user-images.githubusercontent.com/99162086/153635513-8cfa2901-f5b1-4bde-92d3-d778bd6e1731.png) **以下为报错日志** [latest (26).log](https://github.com/DreamVoid/MiraiMC/files/8050408/latest.26.log)
> 
> **服务端版本:**git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) **MiraiMC版本:**1.5.3 这个报错会不会是服务端核心的事情？ **以下为报错截图** ![image](https://user-images.githubusercontent.com/99162086/153637165-5fcf5e09-b5f3-4e08-9d7b-539684dc2fd8.png) **以下为报错日志** [latest (27).log](https://github.com/DreamVoid/MiraiMC/files/8050459/latest.27.log)

服务端应该不会拦截网络，因为MiraiMC已经成功的检测到了更新
**以下为截图**
![image](https://user-images.githubusercontent.com/99162086/153638385-9f15b4fd-3100-4894-bc74-66fb475a2610.png)
**服务端版本**git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
**MiraiMC版本**1.5.3
**以下为日志**
[Uploading latest (28).log…]()

**Comment by DreamVoid** [comment]
> > > > **总结，我测试了以下版本:**MiraiMC-Bukkit 1.6，MiraiMC-Bukkit 1.5.3 **运行环境:** java version "1.8.0_311" Java(TM) SE Runtime Environment (build 1.8.0_311-b11) Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode) **测试环境均为本地测试**:Microsoft Windows 10 x64专业版 10.0.19044 内部版本 19044 **服务端版本:** This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) **MiraiMC-Bukkit 1.6无法加载(以下为运行日志)** [2022-02-09-1.log](https://github.com/DreamVoid/MiraiMC/files/8030578/2022-02-09-1.log) **MiraiMC-Bukkit 1.5.3成功加载，但在登录时报错(以下为运行日志)** [latest.log](https://github.com/DreamVoid/MiraiMC/files/8030599/latest.log)
> > > 
> > > 
> > > 已确认1.6在低版本服务端存在的加载问题，将会在1.6.1或1.7版本修复。
> > > ```
> > > [15:24:22] [Server thread/ERROR]: Class com.google.common.base.Suppliers$MemoizingSupplier does not implement the requested interface java.util.function.Supplier initializing MiraiMC v1.6 (Is it up to date?)
> > > java.lang.IncompatibleClassChangeError: Class com.google.common.base.Suppliers$MemoizingSupplier does not implement the requested interface java.util.function.Supplier
> > > 	at me.dreamvoid.miraimc.internal.MiraiLoader.loadLibraryClass(MiraiLoader.java:125) ~[?:?]
> > > 	at me.dreamvoid.miraimc.internal.MiraiLoader.loadMiraiCore(MiraiLoader.java:28) ~[?:?]
> > > 	at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onLoad(BukkitPlugin.java:29) ~[?:?]
> > > 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:298) [patched_1.8.8.jar:git-PaperSpigot-445]
> > > 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched_1.8.8.jar:git-PaperSpigot-445]
> > > 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
> > > 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 1.5.3版本无法登录是你的服务端有阻止网络连接的行为，可能是代码或者Java内部造成的。
> > > 下次反馈类似问题的时候，我回复之前需要补充相关内容，可以编辑原有评论，不要一直发新的评论。要不然看着很难受，拖慢效率。而且你如果在一开始就把问题描述清楚而不是标1.6却用1.5.3的日志，我很快就能找到问题所在。
> > 
> > 
> > **抱歉，我的操作有点生疏，在上传日志时，我不小心上传了错误的日志，抱歉了，我在使用1.5.3版本时候使用了2个版本的核心进行测试，以下是我的测试结果** 插件成功加载，但在登录时无反应，长时间等待后报错。 **服务端版本:**git-PaperSpigot-f6fba00-9935adc (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) **MiraiMC版本:**1.5.3 **以下为报错截图** ![image](https://user-images.githubusercontent.com/99162086/153635513-8cfa2901-f5b1-4bde-92d3-d778bd6e1731.png) **以下为报错日志** [latest (26).log](https://github.com/DreamVoid/MiraiMC/files/8050408/latest.26.log)
> > **服务端版本:**git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) **MiraiMC版本:**1.5.3 这个报错会不会是服务端核心的事情？ **以下为报错截图** ![image](https://user-images.githubusercontent.com/99162086/153637165-5fcf5e09-b5f3-4e08-9d7b-539684dc2fd8.png) **以下为报错日志** [latest (27).log](https://github.com/DreamVoid/MiraiMC/files/8050459/latest.27.log)
> 
> 服务端应该不会拦截网络，因为MiraiMC已经成功的检测到了更新 **以下为截图** ![image](https://user-images.githubusercontent.com/99162086/153638385-9f15b4fd-3100-4894-bc74-66fb475a2610.png) **服务端版本**git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) **MiraiMC版本**1.5.3 **以下为日志** Uploading latest (28).log…

然而报错的内容显示你的服务器无法解析腾讯服务器的IP地址，要么你的服务器的网络阻止了DNS检查，要么有插件阻止了插件的DNS检查。总之你的服务器无法连接到腾讯的服务器。

**Comment by DreamVoid** [comment]
最新开发版已修复此问题。
