### ISSUE TITLE
无法通过Maven引入MiraiMC依赖：io.github.dreamvoid:MiraiMC-Integration:jar:1.6 的POM文件无效

### ISSUE THREAD

**Issue by XiaMoHuaHuo-CN** [DreamVoid/MiraiMC#125]
### 问题描述

如题，使用的是IDEA 2021.2.3版本，Less233的Maven镜像

### 复现方法

1. 引入MiraiMC Integration

### 服务端类型

Bukkit（包括Paper）

### 服务端版本

spigot-api 1.18-R0.1-SNAPSHOT

### MiraiMC 插件版本

1.6

### 服务端日志

```text
淦，必填那我就填我更新Maven的日志得了
[WARNING] The POM for io.github.dreamvoid:MiraiMC-Integration:jar:1.6 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
```

### 额外说明

Java1.8.0
Windows NT/10 x64
IDEA 2021.2.3
Maven3.6.3
引入Maven来自仓库：
```xml
        <!-- Lss233 Maven repo -->
        <repository>
            <id>lss233-minecraft</id>
            <url>http://lss233.littleservice.cn/repositories/minecraft</url>
        </repository>
        <!-- MvnMavenRepo -->
        <repository>
            <id>mvn-repository</id>
            <url>http://maven.nuxeo.org/nexus/content/groups/public</url>
        </repository>
        <!-- SpigotMavenRepo -->
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
```

**Comment by DreamVoid** [comment]
我也不知道你第1、2个源的意义是什么，如果是镜像应该作为mirror加入而不是原始仓库。
miraimc是在中央仓库的，你要用镜像的话用阿里云的镜像。

**Comment by XiaMoHuaHuo-CN** [comment]
确实是作为镜像使用
第一个是所有相关Minecraft的Maven国内镜像，由Less233搭建，第二个是mvn的Maven镜像，用于获取其他Maven，第三个是备用，因为我这用spigotmc的真的很慢
mirror地址加入的方式我使用阿里源在Maven的settings.xml中曾使用过，结果MC的Maven并不存在于阿里云的Maven镜像

**Comment by DreamVoid** [comment]
> 确实是作为镜像使用
> 第一个是所有相关Minecraft的Maven国内镜像，由Less233搭建，第二个是mvn的Maven镜像，用于获取其他Maven，第三个是备用，因为我这用spigotmc的真的很慢
> mirror地址加入的方式我使用阿里源在Maven的settings.xml中曾使用过，结果MC的Maven并不存在于阿里云的Maven镜像
> 补一句，这样使用我除了引入MiraiMC有问题，其他并无任何问题，包括Bukkit
> 而且IDEA在识别Maven为找到的情况会自动根据仓库标签的排序来进行优先级识别

学习好mirror标签的用法以后，你就会知道如何同时使用阿里云的镜像和lss233的镜像。
