### ISSUE TITLE
提供详细的方法文档

### ISSUE THREAD

**Issue by XiaMoHuaHuo-CN** [DreamVoid/MiraiMC#126]
**功能描述**

如题，给个详细的文档吧（看了下Mirai的文档，很多方法都没在这个项目源码找到
没有谁喜欢一点一点的翻源码看方法

**使用方法**

1. none

**额外说明**

如果没有办法提供就直接把这个Issue关了吧，回复也不需要了

**Comment by DreamVoid** [comment]
你所能用到的都在 docs.miraimc.dreamvoid.ml 不建议使用任何没列出来的方法
