### ISSUE TITLE
1.6的http-api似乎没有用

### ISSUE THREAD

**Issue by IAmNotGEM** [DreamVoid/MiraiMC#129]
### 问题描述

http-api没有用啊，作者你看看。
如果有用的话可以添加一下wiki 吗

### 复现方法

1. 

### 服务端类型

Bukkit

### 服务端版本

CatServer-1.12.2

### MiraiMC 插件版本

1.16

### 服务端日志

```text
无日志，因为无法连接http-api
```

**Comment by DreamVoid** [comment]
我的评价是：
