### ISSUE TITLE
为MiraiGroupMemberJoinEvent和MiraiGroupMemberLeaveEvent添加头像获取和名称获取功能

### ISSUE THREAD

**Issue by XiaMoHuaHuo-CN** [DreamVoid/MiraiMC#147]
### 功能描述

如题
头像获取得到Mirai格式码(String)，名称获取得到用户群名称(String)

### 使用方法

1. 通过Mirai原生方法实现相关功能

**Comment by DreamVoid** [comment]
头像可获取群成员实例后调用相关方法。
