### ISSUE TITLE
关于papi变量可能存在输出错误问题

### ISSUE THREAD

**Issue by JiangQiYan713** [DreamVoid/MiraiMC#153]
### 问题描述

%miraimc_bindname_<qq>%和%miraimc_binduuid_<qq>%可能指向同一个变量

本人插件使用方法：
1.将插件放入/plugins文件夹内
2.start.bat

配置文件未作修改

### 复现方法

1. /papi parse me %miraimc_binduuid_1239273072%
2. 输出为一串UUID
3. /papi parse me %miraimc_bindname_1239273072%
4. 输出仍为一串UUID

【预期行为】
3. /papi parse me %miraimc_bindname_1239273072%
4. 输出为玩家名称，而不是UUID

### 服务端类型

Bukkit

### 服务端版本

paper-1.18.2(git-349)

### MiraiMC 插件版本

1.6.1

### 服务端日志

```text
[10:18:43] [Server thread/INFO]: JiangQiYan issued server command: /papi parse me %miraimc_binduuid_1239273072%
[10:19:07] [Server thread/INFO]: JiangQiYan issued server command: /papi parse me %miraimc_bindname_1239273072%
```
```


### 额外说明

使用依赖插件：
Whitelist4QQ version 1.0 by xingxing520,DreamVoid (MiraiMC version 1.6.1)
Chat2QQ version 1.5 by Dreamvoid (MiraiMC version 1.6.1)

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [ ] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
如果玩家没有进入过服务器，则返回的就是uuid

**Comment by JiangQiYan713** [comment]
啊啊？可是玩家确实已经加入了服务器呀，这两条指令也是以管理员身份在服务器里执行的，而不是服务端控制台

**Comment by DreamVoid** [comment]
> 啊啊？可是玩家确实已经加入了服务器呀，这两条指令也是以管理员身份在服务器里执行的，而不是服务端控制台

1.7重写QQ绑定，看到时候能不能好

**Comment by JiangQiYan713** [comment]
好的 加油www
