### ISSUE TITLE
无法解析 io.github.dreamvoid:MiraiMC:1.6.1

### ISSUE THREAD

**Issue by 1160706050** [DreamVoid/MiraiMC#154]
### 问题描述

io.github.dreamvoid:MiraiMC:pom:1.6.1 was not found in https://hub.spigotmc.org/nexus/content/repositories/snapshots/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of spigotmc-repo has elapsed or updates are forced

### 复现方法

使用模板和IEDA Minecraft Spigot 创建使用该依赖均出现这个问题

![image](https://user-images.githubusercontent.com/37466008/171468760-a8101423-9141-4f12-ac83-406a84ab3a90.png)

### 服务端类型

Bukkit

### 服务端版本

1.18.2

### MiraiMC 插件版本

1.6.1

### 服务端日志

```text
io.github.dreamvoid:MiraiMC:pom:1.6.1 was not found in https://hub.spigotmc.org/nexus/content/repositories/snapshots/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of spigotmc-repo has elapsed or updates are forced

尝试使用 -U 标记(强制更新快照)运行 Maven 导入
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [x] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
自行检查你的网络连接，必要时为maven启用代理。

**Comment by 1160706050** [comment]
> 自行阅读README

![image](https://user-images.githubusercontent.com/37466008/171967769-1f22f220-6ea1-4603-b2f8-d963327494be.png)

我尝试插件jar文件作为外部库直接导入，依旧报错，不使用MiraiMC则正常无报错编译，服务器也正常运行

**Comment by 1160706050** [comment]
![image](https://user-images.githubusercontent.com/37466008/171967847-cb78a0cc-4346-40fe-b4ca-97402aef2b6e.png)
![image](https://user-images.githubusercontent.com/37466008/171967897-c43d0c8c-b564-4fa6-a82c-450c0ffd48c6.png)

**Comment by DreamVoid** [comment]
你这叫什么外部库导入，用maven引用本地jar就应该在pom.xml设置scope，而不是用idea
还有，**自行阅读README**
