### ISSUE TITLE
发送消息报错

### ISSUE THREAD

**Issue by CCBlueX666** [DreamVoid/MiraiMC#169]
### 问题描述

绑定群内收到消息后，后台报错
若使用聊天互通插件，游戏内发消息后，后台报错
若卸载所有插件（除MiraiMC），上述问题依旧存在

### 复现方法

1. 安装MiraiMC
2. 群内或游戏内发一条消息
3. 控制台检查报错

### 服务端类型

Bukkit

### 服务端版本

git-Paper-379 (MC: 1.18.2)

### MiraiMC 插件版本

1.7-pre1

### 服务端日志

```text
见额外说明
```

### 额外说明

[latest.log](https://github.com/DreamVoid/MiraiMC/files/8934773/latest.log)

Java版本：openjdk 17.0.3 2022-04-19 LTS
OpenJDK Runtime Environment Zulu17.34+19-CA (build 17.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.34+19-CA (build 17.0.3+7-LTS, mixed mode, sharing)
插件列表：AdvancedBan, AdvancedBanAutoBan, AdvancedEnchantments, Alias, AllMusic, AncientGates, AntiAttack, AntiGeyserPlayerUUID, AtLite, AuctionHouse, AuthMe, AutoUnloadChunk, BottledExp, **Chat2QQ**, Citizens, CitizensGUI, ClientDetector, CMILib, ConsoleSpamFix, CoreProtect, CrazyCrates, CustomCrafting, DecentHolograms, DriveBackupV2, eBackup, EClean, ErrorFixer, ExtraHeads, FixAuthme, FluffyMachines, Geyser-Spigot, Images, InventoryRollbackPlus, Leastereggs, Libs4Paper, LitePlaytimeRewards, Log4jFix, LuckPerms, LuckPermsGUI, mcMMO, MobCapturer, NBTAPI, NoChatLagServer, OpenInv, OpLogin, packetevents, PlaceholderAPI, Plan, PlayerPoints, PlayerReport, PlayerTitle, PlugManX, PrivateStorage, ProtocolLib, ScoreboardPlus, ServerListPlus, ServerSystem, SimpleJoin, SimpleUtils, SkinsRestorer, Slimefun, SlimefunLuckyBlocks, SlimefunWarfare, SlimeTinker, SoaromaSAC, SQLibrary, TAB, TabCompleteFilter, TileDataSaver, TradeSystem, TranscEndence, TrMenu, UltimateAutoRestart, Vault, ViaVersion, voicechat, **Whitelist4QQ**, WolfyUtilities, WorldEdit, WorldGuard, **XiaoheiConsole, XiaoheiQSManger, MiraiMC**
加粗部分为使用mirai核心的插件
QQ版本是：QQ for Mac V6.7.6(20842)

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by CCBlueX666** [comment]
这个消息无论使用命令发送或正常GUI发送，都会报错

**Comment by CCBlueX666** [comment]
顺便说一句，[mcbbs](https://www.mcbbs.net/thread-1207462-1-1.html)上的指令列表里有一条写错了
<img width="669" alt="image" src="https://user-images.githubusercontent.com/60721270/174466503-ae0465c0-69ff-4209-bc45-467153b885ae.png">
应该是sendgroupmessage

**Comment by devsong42** [comment]
这也是我在1.7-pre1的讨论里说的

**Comment by CCBlueX666** [comment]
> 这也是我在1.7-pre1的讨论里说的

确实，但是上一条issue已经被关闭了，而且没有详细的介绍

**Comment by CCBlueX666** [comment]
此问题在e88d75的构建后仍然存在
at me.dreamvoid.miraimc.bukkit.event.message.postsend.MiraiGroupMessagePostSendEvent.<init>(MiraiGroupMessagePostSendEvent.java:20) ~[MiraiMC-Bukkit.jar:?]
	at me.dreamvoid.miraimc.bukkit.event.MiraiGroupMessagePostSendEvent.<init>(MiraiGroupMessagePostSendEvent.java:13) ~[MiraiMC-Bukkit.jar:?]
与
at me.dreamvoid.miraimc.bukkit.event.message.presend.MiraiGroupMessagePreSendEvent.<init>(MiraiGroupMessagePreSendEvent.java:20) ~[MiraiMC-Bukkit.jar:?]
	at me.dreamvoid.miraimc.bukkit.event.MiraiGroupMessagePreSendEvent.<init>(MiraiGroupMessagePreSendEvent.java:13) ~[MiraiMC-Bukkit.jar:?]

**Comment by devsong42** [comment]
> 此问题在e88d75的构建后仍然存在 at me.dreamvoid.miraimc.bukkit.event.message.postsend.MiraiGroupMessagePostSendEvent.(MiraiGroupMessagePostSendEvent.java:20) ~[MiraiMC-Bukkit.jar:?] at me.dreamvoid.miraimc.bukkit.event.MiraiGroupMessagePostSendEvent.(MiraiGroupMessagePostSendEvent.java:13) ~[MiraiMC-Bukkit.jar:?] 与 at me.dreamvoid.miraimc.bukkit.event.message.presend.MiraiGroupMessagePreSendEvent.(MiraiGroupMessagePreSendEvent.java:20) ~[MiraiMC-Bukkit.jar:?] at me.dreamvoid.miraimc.bukkit.event.MiraiGroupMessagePreSendEvent.(MiraiGroupMessagePreSendEvent.java:13) ~[MiraiMC-Bukkit.jar:?]

你不会自己下了源代码自己构建了jar吧？

**Comment by CCBlueX666** [comment]
> > 此问题在e88d75的构建后仍然存在 at me.dreamvoid.miraimc.bukkit.event.message.postsend.MiraiGroupMessagePostSendEvent.(MiraiGroupMessagePostSendEvent.java:20) ~[MiraiMC-Bukkit.jar:?] at me.dreamvoid.miraimc.bukkit.event.MiraiGroupMessagePostSendEvent.(MiraiGroupMessagePostSendEvent.java:13) ~[MiraiMC-Bukkit.jar:?] 与 at me.dreamvoid.miraimc.bukkit.event.message.presend.MiraiGroupMessagePreSendEvent.(MiraiGroupMessagePreSendEvent.java:20) ~[MiraiMC-Bukkit.jar:?] at me.dreamvoid.miraimc.bukkit.event.MiraiGroupMessagePreSendEvent.(MiraiGroupMessagePreSendEvent.java:13) ~[MiraiMC-Bukkit.jar:?]
> 
> 你不会自己下了源代码自己构建了jar吧？

使用的是action中的Java Cl自动构建

**Comment by CCBlueX666** [comment]
> > 此问题在e88d75的构建后仍然存在 at me.dreamvoid.miraimc.bukkit.event.message.postsend.MiraiGroupMessagePostSendEvent.(MiraiGroupMessagePostSendEvent.java:20) ~[MiraiMC-Bukkit.jar:?] at me.dreamvoid.miraimc.bukkit.event.MiraiGroupMessagePostSendEvent.(MiraiGroupMessagePostSendEvent.java:13) ~[MiraiMC-Bukkit.jar:?] 与 at me.dreamvoid.miraimc.bukkit.event.message.presend.MiraiGroupMessagePreSendEvent.(MiraiGroupMessagePreSendEvent.java:20) ~[MiraiMC-Bukkit.jar:?] at me.dreamvoid.miraimc.bukkit.event.MiraiGroupMessagePreSendEvent.(MiraiGroupMessagePreSendEvent.java:13) ~[MiraiMC-Bukkit.jar:?]
> 
> 你不会自己下了源代码自己构建了jar吧？

https://github.com/DreamVoid/MiraiMC/actions/runs/2522915221
