### ISSUE TITLE
1.7-pre2使用依赖插件提示注册事件已过时

### ISSUE THREAD

**Issue by FrydenSoul** [DreamVoid/MiraiMC#174]
### 问题描述

使用依赖MiraiMC的插件时提示注册事件已过时

### 复现方法

1. 启用MiraiMC及依赖插件
2. 启动服务器

### 服务端类型

Nukkit

### 服务端版本

Nukkit git-785c3b2

### MiraiMC 插件版本

1.7-pre2

### 服务端日志

```text
见额外说明
```

### 额外说明

[server.log](https://github.com/DreamVoid/MiraiMC/files/8935667/server.log)

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [x] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
1.7已调整插件内容，详见更新日志。
