### ISSUE TITLE
1.7-pre2 报错 java.lang.IllegalAccessException

### ISSUE THREAD

**Issue by FrydenSoul** [DreamVoid/MiraiMC#175]
### 问题描述

1.7-pre2加载成功后提示java.lang.IllegalAccessException: Unable to find handler list for event me.dreamvoid.miraimc.nukkit.event.message.passive.AbstractMessageEvent. Static getHandlers method required!，不能正常使用。

### 复现方法

1. 启动服务端

### 服务端类型

Nukkit

### 服务端版本

Nukkit git-785c3b2

### MiraiMC 插件版本

1.7-pre2

### 服务端日志

```text
↓
```

### 额外说明

[server.log](https://github.com/DreamVoid/MiraiMC/files/8940562/server.log)

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [x] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
最新开发版已修复此问题

**Comment by FrydenSoul** [comment]
Thank you Sir

**Comment by FrydenSoul** [comment]
已经发布了吗？
