### ISSUE TITLE
返回值错误

### ISSUE THREAD

**Issue by NoMathExpectation** [DreamVoid/MiraiMC#18]
<strong>问题描述</strong>

使用MiraiGroupMessageEvent的getSenderPermission()方法时，即使发送者是管理员时，返回值也是0

<strong>复现方法</strong>

1. 

<strong>版本类型</strong>

* Minecraft 服务端版本：paper 1.17.1
* MiraiMC 插件编译版本：1.2
MiraiMC 插件运行版本：1.3-pre3

<strong>服务器日志</strong>

```
无
```

**Comment by DreamVoid** [comment]
请尝试使用1.3-pre3版本

**Comment by NoMathExpectation** [comment]
编译用的是1.2，运行用的是1.3-pre3

另外请问这两个包有什么不同吗

**Comment by DreamVoid** [comment]
> 编译用的是1.2，运行用的是1.3-pre3
> 
> 另外请问这两个包有什么不同吗
> 使用的确实是me.dreamvoid.miraimc.event包

有非常大的不同，你看看release的更新日志就知道了
