### ISSUE TITLE
输入登录命令提示 for help type /mirai help

### ISSUE THREAD

**Issue by AisKillaZz** [DreamVoid/MiraiMC#181]
### 问题描述

下载并放入重启服务端，输入登录命令提示 for help type /mirai help，输入任何指令都是for help type /mirai help
怎么解决,是BUG还是什么

### 复现方法

1. 下载并放入重启服务端
2. 输入登录命令提示 for help type /mirai help

### 服务端类型

Bukkit

### 服务端版本

spigot -1.16.5

### MiraiMC 插件版本

1.6.1

### 服务端日志

```text
输入/mirai login 之后服务端弹出
[13:10:25] [Server thread/INFO]: AisKillaZz issued server command: /mirai login
只有这一行
账号密码输入全了也是这样
游戏里面提示for help type /mirai help。服务端没有任何指令
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [x] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by FrydenSoul** [comment]
我记得控制台使用不用带/

**Comment by AisKillaZz** [comment]
> 我记得控制台使用不用带/

那个指令实在游戏里面打的，控制台里面显示出来了，我试过在控制台和游戏里面打命令都是for help type /mirai help

**Comment by ShanZheY** [comment]
我也遇到了这个问题

**Comment by ShanZheY** [comment]
你日志不够详细啊，说了要完整日志

**Comment by AisKillaZz** [comment]
> 你日志不够详细啊，说了要完整日志

我找不到详细的日志，打这个命令没有报错好像，
