### ISSUE TITLE
允许miraimc使用外部mirai

### ISSUE THREAD

**Issue by Shapaper** [DreamVoid/MiraiMC#188]
### 功能描述

允许miraimc使用外部mirai：
我自己制作了一个mirai qq机器人，我另一个机器人用的也是mirai-http-api。
可不可以让miraimc使用mirai-http-api连接到外部的mirai

### 使用方法

1.

**Comment by DreamVoid** [comment]
正在开发

**Comment by Shapaper** [comment]
现在的版本支持了吗
看介绍好像支持了

**Comment by Shapaper** [comment]
HTTP-API是可以开启密钥连接的，这样子会提升安全性，但是配置文件内没有填写密钥的地方

**Comment by DreamVoid** [comment]
> HTTP-API是可以开启密钥连接的，这样子会提升安全性，但是配置文件内没有填写密钥的地方

使用mirai login命令连接，密码部分填写密钥

**Comment by Shapaper** [comment]
az

**Comment by Shapaper** [comment]
我试试

**Comment by Shapaper** [comment]
![image](https://user-images.githubusercontent.com/88654772/177508766-de9238f6-2362-498a-b99e-4bda2da4e71f.png)
zh这个是干嘛用的
