### ISSUE TITLE
MiraiBot Account问题

### ISSUE THREAD

**Issue by Micalhl** [DreamVoid/MiraiMC#2]
很抱歉又打扰你了
MiraiBot#doBotLogin(int, String, BotConfiguration.MiraiProtocol)
为什么第一个参数要求传 int，QQ号码长的话不是超出 Integer 限制了么

后来我查了一下调用的方法 privateBotLogin
但是我发现机器人登录是 BotFactory.INSTANCE.newBot(int, String, BotConfiguration)
说明 Mirai 默认提供的就是 int 账号
到底是怎么回事

**Comment by DreamVoid** [comment]
你的疑问也是我的疑问，我在写插件的时候也注意到了，其他的方法都需要长整数的机器人QQ号，只有登录机器人的时候不需要
我最开始是参照mirai-hello-world开发的，这里面的示例代码直接把机器人QQ号写入代码然后就能运行起来，传的就是int
不过，我还是把int改成了long，稍后发布的1.1-rc4就没有这个问题了

不用怕打扰我，相反我非常需要和你一样的人告诉我Bug然后修复

**Comment by DreamVoid** [comment]
其实，我更倾向于引导用户手动登录机器人，像mirai console一样。

[1.1-rc4](https://github.com/DreamVoid/MiraiMC/releases/tag/v1.1-rc4)已经发布
