### ISSUE TITLE
希望可以更改qslist的存储方式

### ISSUE THREAD

**Issue by zhihan369** [DreamVoid/MiraiMC#205]
### 功能描述

绑定白名单的相关插件使用的是MiraiMC自己的数据库，但是通常他获取的是uuid，这对间歇泉互通很不利，因为基岩版玩家的uuid往往是和java不相同的，所以希望可以修改为保存玩家id而不是uuid

### 使用方法

1. 有额外的设置，要么选择保存uuid要么保存id

**Comment by DreamVoid** [comment]
但是这有什么问题吗，uuid不相同又没关系，又不是同一个人
