### ISSUE TITLE
在群内发送消息时MiraiMC提示Chat2QQ错误

### ISSUE THREAD

**Issue by lightumcc** [DreamVoid/MiraiMC#208]
### 问题描述

如题
我不确定这是否由mirai核心造成

### 复现方法

1. 群里发条消息

### 服务端类型

Bukkit

### 服务端版本

Paper-1.18.2

### MiraiMC 插件版本

1.7

### 服务端日志

```text
见额外说明
```

### 额外说明

legacy-event-support已打开
依赖MiraiMC的只有Chat2QQ插件
chat2qq是1.6
[latest.txt](https://github.com/DreamVoid/MiraiMC/files/9126020/latest.txt)

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by CCBlueX666** [comment]
如果停用Chat2QQ则日志为
[22:43:09 INFO]: [MiraiMC] [GroupMessage/XXXX] [XXXXXX(XXXX)]XXXX(XXXX) -> (这里真的什么都没有)

**Comment by DreamVoid** [comment]
已复现，但不确定是哪方面的问题，明天慢慢测试

**Comment by ObcbO** [comment]
遇到相同问题

**Comment by XuBamboo** [comment]
https://github.com/mamoe/mirai/issues/2127

**Comment by DiamBlog** [comment]
> [mamoe/mirai#2127](https://github.com/mamoe/mirai/issues/2127)

今日我遇到相同问题

**Comment by XiaMoHuaHuo-CN** [comment]
腾讯新增封禁 请使用手机QQ登录Bot打开下方链接
https://accounts.qq.com/safe/message/unlock?lock_info=5_5

**Comment by leslie103** [comment]
> 腾讯新增封禁 请使用手机QQ登录Bot打开下方链接 https://accounts.qq.com/safe/message/unlock?lock_info=5_5

表示没用

**Comment by XiaMoHuaHuo-CN** [comment]
> > 腾讯新增封禁 请使用手机QQ登录Bot打开下方链接 https://accounts.qq.com/safe/message/unlock?lock_info=5_5
> 
> 表示没用

emm 这个我不清楚 反正tx确实新增了个封禁

**Comment by leslie103** [comment]
> 

我是用手机电脑登录的时候没有任何问题 一用miraimc登录就不能收发消息这样

**Comment by TiaTheFairy** [comment]
遇到相同问题。
1.16.5 paper段，
无任何其他依赖Mirai的插件

**Comment by DreamVoid** [comment]
最新开发版已修复（Bukkit）
