### ISSUE TITLE
机器人指定群或好友发送消息可使用变量

### ISSUE THREAD

**Issue by KaridaLee** [DreamVoid/MiraiMC#218]
### 功能描述

使用指令向某个好友发送消息时，消息内可以使用变量，比如消息内使用%player%变量时就可以显示是谁使用了这个功能

### 使用方法

1. 玩家 KaridaLee使用指令/mirai sendfriendmessage [机器人QQ] [好友] %player%申请添加称号，请及时处理
2. [好友]收到的消息 KaridaLee 申请添加称号，请及时处理

### 额外说明

如果能支持除 player 变量之外的其他变量就更好了

**Comment by DreamVoid** [comment]
没有必要，只会变得更加繁琐
