### ISSUE TITLE
使用控制台尝试获取玩家绑定的QQ时出现错误

### ISSUE THREAD

**Issue by Legendans** [DreamVoid/MiraiMC#219]
### 问题描述

搭配 Whitelist4QQ自助绑定插件使用
在控制台使用命令miraimc bind getqq 获取QQ账号绑定昵称时一切正常
在使用miraimc bind getplayer Lean6959 时会出现错误

### 复现方法

1. 控制台使用命令/miraimc bind getplayer Lean6959

### 服务端类型

Bukkit

### 服务端版本

Paper-1.17.1

### MiraiMC 插件版本

1.7

### 服务端日志

```text
[NekoMaid] NekoMaid issued server command: /miraimc bind getplayer Lean6959

[收起][MiraiMC] Plugin MiraiMC v1.7 generated an exception while executing task 641845 java.lang.IllegalArgumentException: Invalid UUID string: Lean6959
	at java.util.UUID.fromString1(UUID.java:280) ~[?:?]
	at java.util.UUID.fromString(UUID.java:258) ~[?:?]
	at me.dreamvoid.miraimc.bukkit.commands.MiraiMcCommand$4.run(MiraiMcCommand.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [patched_1.17.1.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

### 额外说明

win10
Java16
依赖插件有：
Whitelist4QQ
chat2QQ
都是近期下载的最新版

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [ ] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by Legendans** [comment]
> ### 问题描述
> 搭配 Whitelist4QQ自助绑定插件使用 在控制台使用命令miraimc bind getqq 获取QQ账号绑定昵称时一切正常 在使用miraimc bind getplayer Lean6959 时会出现错误
> 
> ### 复现方法
> 1. 控制台使用命令/miraimc bind getplayer Lean6959
> 
> ### 服务端类型
> Bukkit
> 
> ### 服务端版本
> Paper-1.17.1
> 
> ### MiraiMC 插件版本
> 1.7
> 
> ### 服务端日志
> ```
> [NekoMaid] NekoMaid issued server command: /miraimc bind getplayer Lean6959
> 
> [收起][MiraiMC] Plugin MiraiMC v1.7 generated an exception while executing task 641845 java.lang.IllegalArgumentException: Invalid UUID string: Lean6959
> 	at java.util.UUID.fromString1(UUID.java:280) ~[?:?]
> 	at java.util.UUID.fromString(UUID.java:258) ~[?:?]
> 	at me.dreamvoid.miraimc.bukkit.commands.MiraiMcCommand$4.run(MiraiMcCommand.java:93) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-411]
> 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [patched_1.17.1.jar:git-Paper-411]
> 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Paper-411]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
> 	at java.lang.Thread.run(Thread.java:831) [?:?]
> ```
> 
> ### 额外说明
> win10 Java16 依赖插件有： Whitelist4QQ chat2QQ 都是近期下载的最新版
> 
> ### 协议
> * [x]  我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
> * [x]  我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by Legendans** [comment]
一声不吭关闭别人问题，真不错

**Comment by DreamVoid** [comment]
![c](https://user-images.githubusercontent.com/45266046/181494702-0392862f-4294-4d08-9926-c7f3d23c41aa.png)

不会提问题就别提
