### ISSUE TITLE
Kotlin版本不正确，导致机器人无法正常登录.

### ISSUE THREAD

**Issue by Liangbai2333** [DreamVoid/MiraiMC#22]
<strong>问题描述</strong>

在使用MiraiMC插件尝试登录时，出现NoSuchMethodError，并且包名带有kotlin
只安装了三个插件，并且其他插件内没有使用kotlin.
很明显，是kotlin依赖库版本不正确造成的，请作者更新kotlin库至mirai对应版本后再进行release.

另，jdk8 jdk11均已尝试，错误一致.

<strong>复现方法</strong>

1. 只安装一个MiraiMC插件，登录机器人.

<strong>版本类型</strong>

* Minecraft 服务端版本：Arclight-1.0.19-1.16
* MiraiMC 插件版本：1.3.2

<strong>服务器日志</strong>

```
Caused by: java.lang.NoSuchMethodError: kotlin.jvm.internal.MutablePropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
```

**Comment by DreamVoid** [comment]
请提供完整服务器日志以供分析问题所在。

**Comment by Liangbai2333** [comment]
> 请提供完整服务器日志以供分析问题所在。

无实际有用的日志，仅能看出Kotlin版本不正确.

**Comment by DreamVoid** [comment]
无法提供完整服务器日志
