### ISSUE TITLE
自动登录出现错误

### ISSUE THREAD

**Issue by Liangbai2333** [DreamVoid/MiraiMC#23]
<strong>问题描述</strong>

见日志，为何把两个包装对象拿来强转？
... ...

<strong>复现方法</strong>

1. 开启服务器时

<strong>版本类型</strong>

* Minecraft 服务端版本：Uranium-1710-dev-5-B293-f73a12f-server
* MiraiMC 插件版本：1.3.2

<strong>服务器日志</strong>

```
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
        at me.dreamvoid.miraimc.bukkit.MiraiAutoLogin.lambda$doStartUpAutoLogin$0(MiraiAutoLogin.java:79)
```

**Comment by DreamVoid** [comment]
1.3.2已无此问题，请确认你正在使用。
另外，服务器日志请不要只复制原因，若无法根据服务器日志判断代码位置将被认为无效反馈。

**Comment by Liangbai2333** [comment]
> 1.3.2已无此问题，请确认你正在使用。
> 另外，服务器日志请不要只复制原因，若无法根据服务器日志判断代码位置将被认为无效反馈。

我确认我正在使用，代码位置已经给出: MiraiAutoLogin.java:79，Map#get 方法 返回的必然是一个对象，而不是基本类型，至于你说的没问题
我看了一下你的代码，结论是请查看你使用的QQ号是否大于2147483647。
至于解决办法：long Account = (Long) map.get("account"); 括号内Long替换为long，参见JDK1.5，自动拆箱

**Comment by DreamVoid** [comment]
> > 1.3.2已无此问题，请确认你正在使用。
> > 另外，服务器日志请不要只复制原因，若无法根据服务器日志判断代码位置将被认为无效反馈。
> 
> 我确认我正在使用，代码位置已经给出: MiraiAutoLogin.java:79，Map#get 方法 ，由于泛型机制返回的必然是一个对象，而不是基本类型，至于你说的没问题
> 我看了一下你的代码，结论是请查看你使用的QQ号是否大于2147483647。
> 至于解决办法：long Account = (Long) map.get("account"); 括号内Long替换为long，参见JDK1.5，自动拆箱

请见 #20

**Comment by Liangbai2333** [comment]
> > > 1.3.2已无此问题，请确认你正在使用。
> > > 另外，服务器日志请不要只复制原因，若无法根据服务器日志判断代码位置将被认为无效反馈。
> > 
> > 
> > 我确认我正在使用，代码位置已经给出: MiraiAutoLogin.java:79，Map#get 方法 ，由于泛型机制返回的必然是一个对象，而不是基本类型，至于你说的没问题
> > 我看了一下你的代码，结论是请查看你使用的QQ号是否大于2147483647。
> > 至于解决办法：long Account = (Long) map.get("account"); 括号内Long替换为long，参见JDK1.5，自动拆箱
> 
> 请见 #20

那是因为对方的QQ号大于2147483647，是Long对象被你转成Integer了...，为什么要强转成Long呢..

**Comment by youtiaoguagua** [comment]
> > > > > 1.3.2已无此问题，请确认你正在使用。
> > > > > 另外，服务器日志请不要只复制原因，若无法根据服务器日志判断代码位置将被认为无效反馈。
> > > > 
> > > > 
> > > > 我确认我正在使用，代码位置已经给出: MiraiAutoLogin.java:79，Map#get 方法 ，由于泛型机制返回的必然是一个对象，而不是基本类型，至于你说的没问题
> > > > 我看了一下你的代码，结论是请查看你使用的QQ号是否大于2147483647。
> > > > 至于解决办法：long Account = (Long) map.get("account"); 括号内Long替换为long，参见JDK1.5，自动拆箱
> > > 
> > > 
> > > 请见 #20
> > 
> > 
> > 那是因为对方的QQ号大于2147483647，是Long对象被你转成Integer了...，为什么要强转成Long呢..
> 
> `long Account = (long) map.get("account");`
> 修改为此项无法编译通过，这也是我在发布1.3.2时尝试过的
> `不兼容的类型: capture#1, 共 ?无法转换为long`
> 
> 如您有解决方案，请提交 Pull requests，此Issue不会继续跟进

这个问题还是在的，为什么不转换为string，在paserLong？
