### ISSUE TITLE
支持 Fabric 服务端

### ISSUE THREAD

**Issue by chenjj100419** [DreamVoid/MiraiMC#231]
### 功能描述

能否提供fabric版本给生电服使用

### 使用方法

能否提供fabric版本给生电服使用

### 额外说明

能否提供fabric版本给生电服使用

**Comment by DreamVoid** [comment]
我没研究过Fabric，有能力或者有人帮我就支持

**Comment by BeiGuaOvO** [comment]
写mod可以实现，可以自己逝世(

**Comment by CleMooling** [comment]
建议使用mcdr的插件，然后使用go-cqhttp
