### ISSUE TITLE
MiraiGroupMessageEvent时间在调用reply，replyMirai，sendMessage，sendMessageMirai方法均有问题

### ISSUE THREAD

**Issue by 164ebr** [DreamVoid/MiraiMC#234]
### 问题描述

**自行开发附属插件使用event.reply("")以及event.replyMirai("")回应信息均无反应**
![image](https://user-images.githubusercontent.com/86980013/184541981-69c6405f-b6c6-45fa-a4ac-e58395a12781.png)

**经过测试得出结论
MiraiGroupMessageEveent的时候，调用event.reply方法，event.replyMirai方法，event.sendMessage方法，event.sendMessageMirai方法。均向发送者私聊回应。不会在群内回应（盲猜应该是你写错了）**

**下面是我测试代码**
![image](https://user-images.githubusercontent.com/86980013/184541988-c5bc2a2f-b780-46b5-b26a-a44060aa8f96.png)

### 复现方法

@EventHandler
    public void onReplyMessage(MiraiGroupMessageEvent event){
        if (event.getMessage().equals("测试")){
            event.reply("回应reply方法");
            event.replyMirai("回应replyMirai方法");
            event.sendMessage("回应sendMessage方法");
            event.sendMessageMirai("回应sendMessageMirai方法");
        }
    }

### 服务端类型

Bukkit

### 服务端版本

PurPur-1.18.2

### MiraiMC 插件版本

1.7

### 服务端日志

```text
无
```

### 额外说明

无

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [ ] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by 164ebr** [comment]
下个版本希望可以修复吧（已经通过调用mirai代码实现了）

**Comment by DollyDays** [comment]
新版貌似有事件过期的问题，要换一个包
