### ISSUE TITLE
不必要的反斜杠

### ISSUE THREAD

**Issue by NoMathExpectation** [DreamVoid/MiraiMC#25]
<strong>问题描述</strong>

使用MiraiGroupMessageEvent的getMessage方法时,得到的字符串里会出现不必要的反斜杠"\\"

<strong>复现方法</strong>

1. 

<strong>版本类型</strong>

* Minecraft 服务端版本： paper 1.17.1
* MiraiMC 插件版本： 1.3.2

<strong>服务器日志</strong>

```
无
```

**Comment by DreamVoid** [comment]
我在处理群消息的时候用到了Mirai核心的转换到mirai code方法，这样如果消息带有图片等特殊内容就能得到mirai码。
如果有需要的话，可以尝试自行替换掉，或者等我研究一下mirai不同的转换方法得到的内容有什么不同（我印象中Mirai提供了3种方法）

**Comment by NoMathExpectation** [comment]
我用这个方法主要是用于远程执行命令的，不必要的反斜杠会影响命令的执行

就拿下面这条命令来讲：
/tellraw @a {"text":"test","color":"yellow"}

我从qq里发出去，结果从方法里得到的是
/tellraw @a {"text"\\:"test"\\,"color"\\:"yellow"}

一条本来能执行的命令直接不能用了

**Comment by DreamVoid** [comment]
> 我用这个方法主要是用于远程执行命令的，不必要的反斜杠会影响命令的执行
> 
> 就拿下面这条命令来讲：
> /tellraw @A {"text":"test","color":"yellow"}
> 
> 我从qq里发出去，结果从方法里得到的是
> /tellraw @A {"text"\:"test"\,"color"\:"yellow"}
> 
> 一条本来能执行的命令直接不能用了

所以目前你可以使用replace把“\“替换掉，毕竟一般的命令也不会用到这个符号
另外最近回复和改代码可能会暂缓，因为 https://github.com/DreamVoid/DreamVoid

**Comment by DreamVoid** [comment]
此功能已初步完成修复，我已加入新的方法。
请[点击此处](https://docs.mirai.mamoe.net/Messages.html#serializetomiraicode-%E4%B8%8E-tostring-%E7%9A%84%E5%8C%BA%E5%88%AB)以了解新的方法会如何工作

**Comment by DreamVoid** [comment]
等待[dev-5](https://ci.dreamvoid.ml/job/MiraiMC/23/)构建完成后，请及时反馈修复结果。
通常来说，本次修改对你的代码没有影响，因此你可以直接更换插件而无需修改代码。

**Comment by DreamVoid** [comment]
1.4-pre1已发布，Maven中央仓库同步更新。
请使用新增的```getMessageContent()```方法

**Comment by NoMathExpectation** [comment]
ok,这个bug已经被修复了
