### ISSUE TITLE
面板服登录验证链接无法访问

### ISSUE THREAD

**Issue by BaiJiu123** [DreamVoid/MiraiMC#250]
### 问题描述

在登录账号的时候，会显示那个验证链接，我将那个链接复制到浏览器，却显示无法打开，我也没法解决

### 复现方法

1. 直接登录账户

### 服务端类型

Bukkit

### 服务端版本

Paper-1.16.5

### MiraiMC 插件版本

1.7

### 服务端日志

```text
13.10 10:42:14 [服务器] 警告 当前登录的QQ（3049759174）需要滑动验证码验证
13.10 10:42:14 [服务器] 警告 请打开以下链接进行验证
13.10 10:42:14 [服务器] 警告 https://ssl.captcha.qq.com/template/wireless_mqq_captcha.htmltyle=simple&aid=16&uin=3049759174&sid=3564746965273508614&cap_cd=i7m8F9Nv9-uwNe5NUIuNBwAMiPEek4otrjENpC942ENAbEwND_wXMA**&clientype=1&apptype=2
13.10 10:42:14 [服务器] 警告 验证完成后，请输入指令 /miraiverify captcha 3049759174 <ticket>
13.10 10:42:14 [服务器] 警告 如需取消登录，请输入指令 /miraiverify cancel 3049759174
13.10 10:42:14 [服务器] 警告 如需帮助，请参阅: https://docs.miraimc.dreamvoid.me/troubleshoot/verify-guide#slide-captcha
```

### 额外说明

我放出来的可能不太完整，我会尽可能的配合解决问题

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
说明你的浏览器无法访问腾讯服务器。

**Comment by BaiJiu123** [comment]
也不是，在我自己电脑搭建的服务器可以登录那个链接，而在这个面板服的链接无法打开
