### ISSUE TITLE
输入任何命令都是提示/MiraiMC help

### ISSUE THREAD

**Issue by wyblxy** [DreamVoid/MiraiMC#265]
### 问题描述

输入任何命令都是提示/MiraiMC help

### 复现方法

1. 输入任何命令都是提示/MiraiMC help

### 服务端类型

Bukkit

### 服务端版本

1.12.2

### MiraiMC 插件版本

1.7

### 服务端日志

```text
https://pastebin.com/0YBuRxBX
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
使用最新版本
