### ISSUE TITLE
当前QQ版本过低，请升级至最新版本后再登录。MiraiMC1.7.1最新版

### ISSUE THREAD

**Issue by KanyShigure** [DreamVoid/MiraiMC#285]
### 问题描述

之前修复过的问题，但现在并未被完全修复，并反馈了新的报错
提供了详尽的日志
见下方链接

此外原Issues帖还有其他人出现问题的回复

### 复现方法

1. 正常开启服务器
2. 自动登录指定QQ，并弹出需要滑块验证
3. 正确完成滑块验证，产生一些报错（其中部分报错在上一版本和1.7.1构建版本中并未出现）并反馈版本过低

### 服务端类型

Bukkit

### 服务端版本

Mohist version 1.12.2-321

### MiraiMC 插件版本

MiraiMC version 1.7.1

### 服务端日志

```text
相关报错（Ctrl+f检索mirai字符复制所在行，简洁明了）：https://pastes.dev/kiNt5fdxAM
详尽的当次运行所有日志（由于有forge的相关，导致长达16877行，慎用）：https://pastes.dev/BuT3R7pstX
```

### 额外说明

系统：Linux无图形化系统
JAVA：JZULU-1.8

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
使用 mirai 2.13.2

**Comment by Shiroiame-Kusu** [comment]
https://github.com/DreamVoid/MiraiMC/issues/322#issuecomment-1399120614
