### ISSUE TITLE
建议加入一些监测

### ISSUE THREAD

**Issue by Syscat20** [DreamVoid/MiraiMC#29]
<strong>功能描述</strong>

服务器使用了EssentialsX、QuickShop、AuthMe等插件，并且Bot处设置了在游戏内无需前缀也可以向群聊发送消息。
但玩家进入服务器且未登录时、玩家被"/mute"禁言时、玩家按部分插件要求在聊天栏键入数值时，键入的内容都可以被发送到群聊内。
希望可以改进一下，避免出现这种情况。

<strong>使用方法</strong>

1.

**Comment by DreamVoid** [comment]
MiraiMC不存在你所描述的相关功能，你是否正在反馈[Chat2QQ](https://github.com/DreamVoid/Chat2QQ)的问题？

**Comment by Syscat20** [comment]
> MiraiMC不存在你所描述的相关功能，你是否正在反馈[Chat2QQ](https://github.com/DreamVoid/Chat2QQ)的问题？

啊是的，投错了不好意思（
