### ISSUE TITLE
能否添加对间歇泉的支持，基岩版玩家无法绑定

### ISSUE THREAD

**Issue by doubiovo** [DreamVoid/MiraiMC#326]
### 功能描述

我服务器是互通服，添加间歇泉和floodgate。在使用whitelist4qq后，基岩版绑定完无法进服，通过miraimc bind getqq查询显示null。那个白名单插件走的是miraimc的数据库，所以我感觉应该是在mirai这出问题了。虽然那个插件可以设置不使用miraimc数据库，但是自带的存储无法阻止一个QQ绑定多ID

### 使用方法

1. 如题

**Comment by DreamVoid** [comment]
把话说清楚了再来提意见

**Comment by doubiovo** [comment]
间歇泉进入的基岩版玩家在miraimc绑定了游戏ID后仍然无法进入，miraimc那个databse数据库不是按uuid和qq号存储吗，基岩版玩家uuid应该是000000000-00000000000-xxxxx，他db文件里的那个uuid对不上。

**Comment by XiaMoHuaHuo-CN** [comment]
> 间歇泉进入的基岩版玩家在miraimc绑定了游戏ID后仍然无法进入，miraimc那个databse数据库不是按uuid和qq号存储吗，基岩版玩家uuid应该是000000000-00000000000-xxxxx，他db文件里的那个uuid对不上。

试试我这个(
https://github.com/XiaMoHuaHuo-CN/CatSero
