### ISSUE TITLE
支持撤回群消息操作

### ISSUE THREAD

**Issue by xiantiao233** [DreamVoid/MiraiMC#333]
### 功能描述

支持撤回群消息操作

### 使用方法

可以撤回群内消息

**Comment by DreamVoid** [comment]
https://github.com/DreamVoid/MiraiMC/blob/630058e768f513361d4e3e854c413997b37df7db/MiraiMC-Bukkit/src/main/java/me/dreamvoid/miraimc/bukkit/event/message/passive/MiraiGroupMessageEvent.java#L177-L191

**Comment by xiantiao233** [comment]
我的意思是可以随时撤回消息，不是事件触发撤回
比如我想做一个批量撤回群成员发的消息

**Comment by DreamVoid** [comment]
> 我的意思是可以随时撤回消息，不是事件触发撤回 比如我想做一个批量撤回群成员发的消息

没有这种操作
