### ISSUE TITLE
关于在Bungee运行的MiraiMc,添加指令权限功能

### ISSUE THREAD

**Issue by xiantiao233** [DreamVoid/MiraiMC#351]
### 功能描述

如果使用的是Bungee的MiraiMc，由于没有GUI界面，输入登入时的滑动验证码只能用CMD窗口,而网页返回的Key过长
如果尝试在游戏内登入，给了Bungee的admin权限还是无法使用/mirai login

### 使用方法

1. 添加指令权限组

**Comment by DreamVoid** [comment]
插件本来就不是设计给在游戏中运行的

**Comment by xiantiao233** [comment]
我是在想如果添加了，登入机器人会容易许多
