### ISSUE TITLE
建议加入发送图片、语音等的功能

### ISSUE THREAD

**Issue by Maplefstar** [DreamVoid/MiraiMC#37]
<strong>功能描述</strong>

在 MiraiBot 中提供一个方法，能向指定群发送图片、语音等消息
该方法可以接收图库 url 字符串、base64 编码字符串、本地文件路径字符串等作为参数，方便开发者调用

<strong>使用方法</strong>

1. 调用该方法

**Comment by DreamVoid** [comment]
已加入开发计划。
如果着急使用的话，可以先学习Mirai核心提供的MessageChain实现。

**Comment by Maplefstar** [comment]
感谢深夜回复。
一小时前我已阅读相关开发手册，并已掌握了使用messagechain的相关知识。本想删除该issue，但想到原mirai的功能因非常强大而略显臃肿，所以或可开发更轻量的接口以供调用，于是保留。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月2日(周四) 凌晨1:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DreamVoid/MiraiMC] 建议加入发送图片、语音等的功能 (#37)




 
已加入开发计划。
 如果着急使用的话，可以先学习Mirai核心提供的MessageChain进行实现。

**Comment by DreamVoid** [comment]
已在 ```MiraiBot``` 下属子类添加方法 ```sendMessageMirai()```，待最新开发版或1.4-pre2发布后请改用此方法，原有直接发送消息链的方法将被弃用并移除。
上传图片、文件等方法会很快跟进。
