### ISSUE TITLE
关于http-api连接的问题与最近出现的协议问题

### ISSUE THREAD

**Issue by ZoruaFox** [DreamVoid/MiraiMC#370]
### 问题描述

最近QQ出现了强迫用户升级QQ新版本的操作，导致以mirai为核心的机器人出现大范围`code=45 235 238`等错误而登录失败，在查阅MiraiMC相关文档后发现可以使用http-api链接，但是在使用这种连接时，发现连接成功后控制台收到的消息是null，但是其他插件显示，null之后依然包含正确的消息。
详细日志及关键信息见下文

### 复现方法

1. 使用**mcl 2.1.2**登录QQ帐号（利用**fix-protocol-version1.1.0**绕过协议）
2. 启动服务器（已在config中设置`enable-http-api`为true，对端mirai-api-http版本为`2.9.1`）
3. 使用`/mirai login <机器人账号> <连接密钥> HTTPAPI`连接，并看到提示`<QQ号> HTTP-API登录成功！`
4. 尝试发送日志，控制台显示接收到的消息如下
“[MiraiMC] [GroupMessage/_**Bot Number**_] [_**Group Number**_] Zorua_Shi(_**QQNumber**_) -> null”

### 服务端类型

Bukkit

### 服务端版本

Paper  git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)

### MiraiMC 插件版本

MiraiMC 1.8-pre1 

### 服务端日志

```text
见额外说明
```

### 额外说明

[latest.log](https://github.com/DreamVoid/MiraiMC/files/10942107/latest.log)
对上述信息的补充解释：
mcl使用的mirai-core为`2.14.0`，MiraiMC使用的mirai-core为`2.14.0-RC`
http-api、fix-protocol-version版本已在上文列出
如有缺漏，请直接回复，我将第一时间提供。
（P.S.我清楚对MCL的支持仍处在实验阶段，但对于当下腾讯的恶心做法，这只能是唯一的出路）

### 协议

- [x] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by XiaMoHuaHuo-CN** [comment]
可以改用sms模式验证 稳定性是差不多的

**Comment by ZoruaFox** [comment]
> 可以改用sms模式验证 稳定性是差不多的
> 
> https://mirai.mamoe.net/topic/1653/%E5%8D%87%E7%BA%A7-mirai-%E8%87%B3-2-14-0-%E4%BD%BF%E7%94%A8%E6%96%B0%E7%9A%84%E7%9F%AD%E4%BF%A1%E9%AA%8C%E8%AF%81%E6%96%B9%E6%B3%95%E8%A7%A3%E5%86%B3%E8%AE%BE%E5%A4%87%E9%AA%8C%E8%AF%81

根据mirai论坛上的说法，这个sms模式是在滑动验证的ticket输入后自动弹出的，但是我现在的情况是ticket一输完就出现code=235

**Comment by cssxsh** [comment]
> 是ticket一输完就出现code=235

https://mirai.mamoe.net/topic/223

**Comment by ZoruaFox** [comment]
> > 是ticket一输完就出现code=235
> 
> https://mirai.mamoe.net/topic/223

ANDROID_PHONE和ANDROID_PAD是code=235，ANDROID_WATCH是code=238，那现在可不可以理解为账号本身被QQ风控了需要在实体机客户端上挂一段时间才可以解除
(P.S. fix-protocol-version结合Aoki的方法确实可以使mcl登录账号，但是miraimc目前貌似还没有整合进这个解决方案)

**Comment by ZoruaFox** [comment]
> > > 是ticket一输完就出现code=235
> > 
> > https://mirai.mamoe.net/topic/223
> 
> ANDROID_PHONE和ANDROID_PAD是code=235，ANDROID_WATCH是code=238，那现在可不可以理解为账号本身被QQ风控了需要在实体机客户端上挂一段时间才可以解除
> (P.S. fix-protocol-version结合Aoki的方法确实可以使mcl登录账号，但是miraimc目前貌似还没有整合进这个解决方案)

P.P.S 现在的code=235 238是指miraimc，不是mcl。mcl使用[这个方法](https://mirai.mamoe.net/topic/223)可以解决

**Comment by DreamVoid** [comment]
mirai核心请使用2.14.0而不是2.14.0-RC

**Comment by DreamVoid** [comment]
mirai核心请使用2.14.0而不是2.14.0-RC

**Comment by cssxsh** [comment]
@DreamVoid 
2.14 也不顶用

https://github.com/mamoe/mirai/pull

完整修复得等 2.15 了

**Comment by ZoruaFox** [comment]
> mirai核心请使用2.14.0而不是2.14.0-RC

两个都试过了，都没啥用

**Comment by DreamVoid** [comment]
http api日志拿到的消息是null为已知问题，插件能否拿到消息取决于插件用的什么方法。无法登陆的问题我找个时间测试一下，我的8个QQ号已经身经百战不会风控了所以难以复现，加之最近在忙别的项目所以不保证什么时候修复。

**Comment by ZoruaFox** [comment]
> http api日志拿到的消息是null为已知问题，插件能否拿到消息取决于插件用的什么方法。无法登陆的问题我找个时间测试一下，我的8个QQ号已经身经百战不会风控了所以难以复现，加之最近在忙别的项目所以不保证什么时候修复。

那就应该主要是最近风控的问题，关于http-api的问题就辛苦了，先加个won't fix，等mirai上游更新吧

**Comment by ZoruaFox** [comment]
吐槽一下，QQ9都这么长时间了，推进进度都这么慢，慢就慢吧还禁掉一堆协议

**Comment by reezhu** [comment]
引入fix-protocol-version在preLoad过程的最后调用FixProtocolVersion.update(); 可以临时解决这个问题
下面是我的修改，需要预先把fix的jar手工install到了本地


Index: MiraiMC-Base/pom.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/MiraiMC-Base/pom.xml b/MiraiMC-Base/pom.xml
--- a/MiraiMC-Base/pom.xml	(revision ed4ecbd4b682b26d1cb600d0b839c918c39cc2fe)
+++ b/MiraiMC-Base/pom.xml	(date 1678848570469)
@@ -46,6 +46,14 @@
             <version>2.10.1</version>
             <scope>provided</scope>
         </dependency>
+        <dependency>
+            <groupId>xyz.cssxsh.mirai.tool</groupId>
+            <artifactId>fix-protocol-version</artifactId>
+            <version>1.3</version>
+            <scope>compile</scope>
+
+
+        </dependency>
     </dependencies>
 
     <build>
Index: MiraiMC-Base/src/main/java/me/dreamvoid/miraimc/MiraiMCPlugin.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/MiraiMC-Base/src/main/java/me/dreamvoid/miraimc/MiraiMCPlugin.java b/MiraiMC-Base/src/main/java/me/dreamvoid/miraimc/MiraiMCPlugin.java
--- a/MiraiMC-Base/src/main/java/me/dreamvoid/miraimc/MiraiMCPlugin.java	(revision ed4ecbd4b682b26d1cb600d0b839c918c39cc2fe)
+++ b/MiraiMC-Base/src/main/java/me/dreamvoid/miraimc/MiraiMCPlugin.java	(date 1678852542050)
@@ -6,12 +6,15 @@
 import me.dreamvoid.miraimc.internal.Utils;
 import me.dreamvoid.miraimc.internal.libloader.MiraiLoader;
 import me.dreamvoid.miraimc.internal.webapi.Info;
+import net.mamoe.mirai.utils.BotConfiguration;
 import org.xml.sax.SAXException;
+import xyz.cssxsh.mirai.tool.FixProtocolVersion;
 
 import javax.xml.parsers.ParserConfigurationException;
 import java.io.IOException;
 import java.sql.SQLException;
 import java.util.List;
+import java.util.Map;
 
 public class MiraiMCPlugin {
     public static MiraiMCPlugin INSTANCE;
@@ -63,6 +66,8 @@
         } else {
             MiraiLoader.loadMiraiCore(MiraiMCConfig.General.MiraiCoreVersion);
         }
+        FixProtocolVersion.update();
+        Map<BotConfiguration.MiraiProtocol, String> info = FixProtocolVersion.info();
 
         platform.getPluginLogger().info("Pre-load tasks finished.");
     }

**Comment by ZoruaFox** [comment]
> 引入fix-protocol-version在preLoad过程的最后调用FixProtocolVersion.update(); 可以临时解决这个问题 下面是我的修改，需要预先把fix的jar手工install到了本地
> 
> ```
> 
> Index: MiraiMC-Base/pom.xml
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/MiraiMC-Base/pom.xml b/MiraiMC-Base/pom.xml
> --- a/MiraiMC-Base/pom.xml	(revision ed4ecbd4b682b26d1cb600d0b839c918c39cc2fe)
> +++ b/MiraiMC-Base/pom.xml	(date 1678848570469)
> @@ -46,6 +46,14 @@
>              <version>2.10.1</version>
>              <scope>provided</scope>
>          </dependency>
> +        <dependency>
> +            <groupId>xyz.cssxsh.mirai.tool</groupId>
> +            <artifactId>fix-protocol-version</artifactId>
> +            <version>1.3</version>
> +            <scope>compile</scope>
> +
> +
> +        </dependency>
>      </dependencies>
>  
>      <build>
> Index: MiraiMC-Base/src/main/java/me/dreamvoid/miraimc/MiraiMCPlugin.java
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/MiraiMC-Base/src/main/java/me/dreamvoid/miraimc/MiraiMCPlugin.java b/MiraiMC-Base/src/main/java/me/dreamvoid/miraimc/MiraiMCPlugin.java
> --- a/MiraiMC-Base/src/main/java/me/dreamvoid/miraimc/MiraiMCPlugin.java	(revision ed4ecbd4b682b26d1cb600d0b839c918c39cc2fe)
> +++ b/MiraiMC-Base/src/main/java/me/dreamvoid/miraimc/MiraiMCPlugin.java	(date 1678852542050)
> @@ -6,12 +6,15 @@
>  import me.dreamvoid.miraimc.internal.Utils;
>  import me.dreamvoid.miraimc.internal.libloader.MiraiLoader;
>  import me.dreamvoid.miraimc.internal.webapi.Info;
> +import net.mamoe.mirai.utils.BotConfiguration;
>  import org.xml.sax.SAXException;
> +import xyz.cssxsh.mirai.tool.FixProtocolVersion;
>  
>  import javax.xml.parsers.ParserConfigurationException;
>  import java.io.IOException;
>  import java.sql.SQLException;
>  import java.util.List;
> +import java.util.Map;
>  
>  public class MiraiMCPlugin {
>      public static MiraiMCPlugin INSTANCE;
> @@ -63,6 +66,8 @@
>          } else {
>              MiraiLoader.loadMiraiCore(MiraiMCConfig.General.MiraiCoreVersion);
>          }
> +        FixProtocolVersion.update();
> +        Map<BotConfiguration.MiraiProtocol, String> info = FixProtocolVersion.info();
>  
>          platform.getPluginLogger().info("Pre-load tasks finished.");
>      }
> ```

可以提交一个pr，然后进Action Cl构建一个临时修复版本

**Comment by reezhu** [comment]
> fix-protocol-version

我有提到fix-protocol-version是我手工提交到本地仓库的，他们并没有发布在正式的仓库中，所以默认是拉不到这个依赖的
