### ISSUE TITLE
无法登录机器人，出现 `code=237`

### ISSUE THREAD

**Issue by jhqwqmc** [DreamVoid/MiraiMC#373]
### 问题描述

使用密码登录提供验证码就会提示237问题

### 复现方法

1.用密码登录
2.按要求通过滑动验证码

### 服务端类型

Bukkit

### 服务端版本

git-KeYi-develop/1.19.3-88081c7 (MC: 1.19.3)

### MiraiMC 插件版本

1.8-pre1

### 服务端日志

```text
见额外说明
```

### 额外说明

日志链接: https://mclo.gs/zXcSiHb
日志文件: [2023-03-12-4.log.gz](https://github.com/DreamVoid/MiraiMC/files/10950104/2023-03-12-4.log.gz)
系统: Windows Server 2019 10.0 (amd64)
Java版本: Java 18 (Java HotSpot(TM) 64-Bit Server VM 18.0.2.1+1-1) 
使用依赖MiraiMC的插件: Chat2QQ, Link2QQ
通过提供的解决方法也无法解决,建议添加一个直接使用手机验证码登录的方法

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by ZoruaFox** [comment]
#370 ，issue重复

**Comment by DreamVoid** [comment]
尝试使用最新的mirai核心

**Comment by HaiXi2912** [comment]
更新新的lib后依旧是“ code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。”

**Comment by DreamVoid** [comment]
最新开发版已添加扫码登录，用法：`/mirai login 机器人QQ QRCode ANDROID_WATCH`
即密码处填写“QRCode”，协议填写“ANDROID_WATCH”就会调用扫码登录。
另外长期没有得到回复，视为已解决问题。
