### ISSUE TITLE
调用MiraiGroupMessageEvent时出现警告，并且无法使用

### ISSUE THREAD

**Issue by DICEALPHAHU** [DreamVoid/MiraiMC#382]
### 问题描述

定制插件调用MiraiGroupMessageEvent时出现警告，并且无法使用

该插件的下载地址
[蓝奏云下载](https://wwwy.lanzoum.com/i1Tt20r5fz4h)
其中引用这部分的语法
`//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package cn.shpries.alphahu.alphahubot;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import me.dreamvoid.miraimc.api.MiraiBot;
import me.dreamvoid.miraimc.bukkit.event.MiraiGroupMessageEvent;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;

public class MessageListener implements Listener {
    public MessageListener() {
    }

    @EventHandler
    public void onGroupMessage(MiraiGroupMessageEvent var1) {
        if (var1.getMessage().equals("#人数")) {
            MiraiBot.getBot(var1.getBotID()).getGroup(var1.getGroupID()).sendMessage("服务器在线玩家数：" + Bukkit.getServer().getOnlinePlayers().size());
            List var2 = (List)Bukkit.getOnlinePlayers();
            List<String> var3 = new ArrayList();
            Iterator var4 = var2.iterator();

            while(var4.hasNext()) {
                Object var5 = var4.next();
                String var6 = ((Player)var5).getName();
                var3.add(var6);
            }

            MiraiBot.getBot(var1.getBotID()).getGroup(var1.getGroupID()).sendMessage("目前在线玩家: " + var3);
        }

    }
}`

### 复现方法

1. 正常启用服务器并且启用了miraimc
2. 启动过程中出现以下报错
3. 详见服务器端日志

### 服务端类型

Bukkit

### 服务端版本

Purpur-1.19.2-1858.jar

### MiraiMC 插件版本

version 1.8-pre1

### 服务端日志

```text
[17:29:10 WARN]: [AlphahuBot] Loaded class me.dreamvoid.miraimc.bukkit.event.MiraiGroupMessageEvent from MiraiMC v1.8-pre1 which is not a depend or softdepend of this plugin.
[17:29:10 WARN]: [AlphahuBot] "AlphahuBot v1.0" has registered a listener for me.dreamvoid.miraimc.bukkit.event.MiraiGroupMessageEvent on method "public void cn.shpries.alphahu.alphahubot.MessageListener.onGroupMessage(me.dreamvoid.miraimc.bukkit.event.MiraiGroupMessageEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [].
```

### 额外说明

这个插件用于查询服务器的玩家人数，在群里输入#人数，群聊机器人就会返回人数以及玩家
这个类似乎被“荒废”了，我该如何重新调用这个类呢？

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DICEALPHAHU** [comment]
补充一下这个类的地址
[](https://github.com/DreamVoid/MiraiMC/blob/main/MiraiMC-Bukkit/src/main/java/me/dreamvoid/miraimc/bukkit/event/MiraiGroupMessageEvent.java)

**Comment by DICEALPHAHU** [comment]
补充一下这个类的地址
[MiraiGroupMessageEvent.java](https://github.com/DreamVoid/MiraiMC/blob/main/MiraiMC-Bukkit/src/main/java/me/dreamvoid/miraimc/bukkit/event/MiraiGroupMessageEvent.java)

**Comment by DreamVoid** [comment]
使用 `me.dreamvoid.miraimc.bukkit.event.message.passive.MiraiGroupMessageEvent`
