### ISSUE TITLE
添加对Mirai 2.15.0-M1的支持

### ISSUE THREAD

**Issue by Zhou-Shilin** [DreamVoid/MiraiMC#386]
### 功能描述

如题，希望添加对Mirai 2.15.0-M1的支持。
该版本疑似修复了45报错（qq版本过低），并支持了扫码登录。
[Github Release](https://github.com/mamoe/mirai/releases/tag/v2.15.0-M1)

### 使用方法

None

### 额外说明

None

**Comment by DreamVoid** [comment]
https://github.com/DreamVoid/MiraiMC/issues/373
