### ISSUE TITLE
希望支持对接go-cqhttp

### ISSUE THREAD

**Issue by CleMooling** [DreamVoid/MiraiMC#389]
### 功能描述

如题，希望可以像远程支持mcl那样支持go-cqhttp（应该不会很难，提出这个请求是因为go-cqhttp上我能够正常登录使用）。
另外，最新版的miraimc无法通过任何方式触发扫码登录和手机验证码登录（如果有希望能提供方法），滑条验证码必定无法通过验证，100%触发code=237（已经登录成功过的即使是在相同设备网络环境下重启服务器也会出现这种情况，比如我）！！！
如果可行，希望后续淘汰滑条，很容易登不上去）

### 使用方法

1.  null

**Comment by DreamVoid** [comment]
没有兴趣，除非你来写
