### ISSUE TITLE
希望支持手表等协议扫码登录

### ISSUE THREAD

**Issue by CleMooling** [DreamVoid/MiraiMC#392]
### 功能描述

如题，滑动验证码真的栓Q了，通过密码登录以及滑动验证码基本登不上账号
目前没有发现能触发扫码登录的方法，因此提出这个请求（按理来说如果用手表协议进行扫码登录，应该不会也没有理由出现发送滑条验证码进行验证的情况，但是我改协议后尝试登录发现还是要滑条）
je没找到其他能用的机器人插件了，如果不能实现，我很抱歉打扰了

### 使用方法

1. null

**Comment by CleMooling** [comment]
滑条会出现code=237和45（版本过低），目前在我有的账号上基本无法解决（包括在局域网环境下操作）

**Comment by DreamVoid** [comment]
要不然你来写吧，也不看看mirai支不支持扫码，老是开无效issue有什么意义？
