### ISSUE TITLE
Aoki可以正常登陆 放到服务器上不行

### ISSUE THREAD

**Issue by CCjun6** [DreamVoid/MiraiMC#393]
### 功能描述

我试用Aoki软件 成功用MACOS的协议登陆成功
但是我按照教程 把bots转移到服务器然后继续登陆 确无法成功 code=45

### 使用方法

1.

**Comment by ApliNi** [comment]
似乎 mirai-2.14.0 必须配合 fix-protocol-version 插件才能使用
而 mirai-2.15.0-M1 移除了短信验证登录, 必须扫码, 但 miraiMC 还不支持
