### ISSUE TITLE
1.8-pre1QQ版本过低

### ISSUE THREAD

**Issue by anxge** [DreamVoid/MiraiMC#397]
### 问题描述

1.8-pre1登录显示QQ版本过低

### 复现方法

1. 自动登录显示无法登录
2. 手动登录显示版本过低，返回null

### 服务端类型

Bukkit

### 服务端版本

spigot-1.19.4

### MiraiMC 插件版本

1.8-pre1

### 服务端日志

```text
分成两份还是超出限制
已在额外说明上传文件
望理解
```

### 额外说明

[latest.log](https://github.com/DreamVoid/MiraiMC/files/11518982/latest.log)

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
参考https://github.com/DreamVoid/MiraiMC/issues/373
