### ISSUE TITLE
服务器登录bot打开链接返回404

### ISSUE THREAD

**Issue by serverbread** [DreamVoid/MiraiMC#407]
### 问题描述

我在输入了指令/mirai login ID passwd IPAD 之后打开显示的链接（使用edge浏览器）然后这个网页给我返回了404：
![图片](https://github.com/DreamVoid/MiraiMC/assets/119761840/50a40ae7-fcf3-401c-a021-28906a1cc7be)

### 复现方法

1. 在控制台输入指令mirai login <ID> <passwd> IPAD
2. 用edge打开弹出的链接
3. 出现上述问题

### 服务端类型

Bukkit

### 服务端版本

git-Leaves-"6769d55" (MC: 1.19.4)

### MiraiMC 插件版本

1.8-pre2

### 服务端日志

```text
超出字数，已将日志放在下述额外说明
```

### 额外说明

我将[日志](https://mclo.gs/wXZlfRL)放在了mclog

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
<img width="633" alt="image" src="https://github.com/DreamVoid/MiraiMC/assets/45266046/63afdba6-4d97-417a-b987-311ab3044f27">

**Comment by serverbread** [comment]
我使用了firefox再测试了一遍，结果是空白页面（网络界面能发现404）

**Comment by serverbread** [comment]
> <img alt="image" width="633" src="https://user-images.githubusercontent.com/45266046/244923198-63afdba6-4d97-417a-b987-311ab3044f27.png">

实测仍无法复现
![图片](https://github.com/DreamVoid/MiraiMC/assets/119761840/5152383e-8197-46a9-88a2-a7f2ce4987f6)

**Comment by serverbread** [comment]
已找到问题：旋律云面板将连接："html?style"部分的"?s"吞掉导致这部分链接变成了"htmltyle"，改回正常
