### ISSUE TITLE
MiraiMC机器人无法登陆，QQ版本过低，含多条报错

### ISSUE THREAD

**Issue by KanyShigure** [DreamVoid/MiraiMC#411]
### 问题描述

在私人电脑上测试插件，发现MiraiMC机器人登录不上去了，前几日还正常使用
具体表现为登陆机器人时产生多条QQ版本过低的报错，同时无法登陆
config仅将log-events改为了true
附详细日志

### 复现方法

正常使用就触发了

### 服务端类型

Bukkit

### 服务端版本

Mohist-1.12.2

### MiraiMC 插件版本

1.8-pre2

### 服务端日志

```text
https://pastes.dev/5uohaKzFao
```

### 额外说明

系统：Win10
JAVA：ZULU-JDK8
MiraiMC附属：Chat2qq

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by serverbread** [comment]
我觉得你应该把这个问题报告到[mirai](https://github.com/mamoe/mirai/issues/new?assignees=&labels=z%3Aquestion&projects=&template=bug.yml)？
