### ISSUE TITLE
无法登录机器人，出现 code=45    后续下载最新mirai核心，扫码登录，登录失败

### ISSUE THREAD

**Issue by Cula6** [DreamVoid/MiraiMC#419]
### 问题描述

首先正常登录/mirai login QQ号 密码  
滑块验证结束后   出现
WrongPasswordException: Error(bot=Bot(1498465117), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
[16:53:23] [DefaultDispatcher-worker-4/WARN]: [MiraiMC] Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.auth.ProducerFailureException)
[16:53:23] [nioEventLoopGroup-14-3/INFO]: [MiraiMC] Bot cancelled: Bot closed
[16:53:23] [Craft Scheduler Thread - 185/WARN]: [MiraiMC] 登录机器人时出现异常，原因: null
随后下载最新mirai核心，扫码登录出现
![Uploading Screenshot_2023-06-26-16-54-43-486_com.tencent.mo.jpg…]()

### 复现方法

复现方法没有特殊情况
就是正常滑块登录
正常扫码登录

### 服务端类型

Bukkit

### 服务端版本

spiogt-1.20.1

### MiraiMC 插件版本

1.8-pre2

### 服务端日志

```text
服务器日志已在额外说明提供
```

### 额外说明

[latest.log](https://github.com/DreamVoid/MiraiMC/files/11866421/latest.log)
我所使用的是vps   1.20.1-spigot基岩Java互通服
Java-17

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by Cula6** [comment]
扫码登录失败：
当前设备网络不稳定或处于复杂网络环境，为了你的帐号安全,建议将两个设备连接同一网络或将被扫描设备连接你的手机热点后，重新扫码登录。

**Comment by DreamVoid** [comment]
复现步骤不要想当然
