### ISSUE TITLE
面板服(Linuxx86)遇到的问题

### ISSUE THREAD

**Issue by xiaotiecshijie** [DreamVoid/MiraiMC#422]
### 问题描述

1.登录时显示QQ版本过低(Android_phone协议)，net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2105068802), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
2.Android_watch协议时无法使用扫码或短信验证码

### 复现方法

1. 面板服(Linuxx86)(简幻欢)使用Android_phone时会出现QQ版本低
2. 面板服(Linuxx86)(简幻欢)使用Android_watch时没有短信验证或扫码登录

### 服务端类型

Bukkit

### 服务端版本

leaves-1.20.1

### MiraiMC 插件版本

1.8-pre1

### 服务端日志

```text
https://xiaotiecshijie.lanzoue.com/iove211fkrvg
由于文件文字太多了 只能弄成蓝奏云了...
```

### 额外说明

JAVA19

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
在这里粘贴服务端日志并把链接给我：

- https://mclo.gs/
- https://paste.denizenscript.com/New/Log
