### ISSUE TITLE
启用插件时出现错误

### ISSUE THREAD

**Issue by ZoruaFox** [DreamVoid/MiraiMC#424]
### 问题描述

在启动MC服务端（Purpur 1.20.1）时无法加载MiraiMC，报错并自动退出。

### 复现方法

1. 启动服务端
2. MiraiMC报错后被服务端跳过

### 服务端类型

Bukkit

### 服务端版本

Purpur-2011

### MiraiMC 插件版本

MiraiMC 1.8-pre2

### 服务端日志

```text
日志过长，已使用mclogs作为剪贴板。
https://mclo.gs/6gmgJPh
```

### 额外说明

系统版本：Windows Server 2022
Java：1.17.5
重置配置后问题仍在（database.db未重置）
使用LinearBot作为附属插件

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
与TabooLib不兼容，请移除TrChat

**Comment by ZoruaFox** [comment]
已确认MiraiMC默认`mirai-core-version`为stable时会出现此错误，请将此配置项默认值调整为latest。

**Comment by DreamVoid** [comment]
开发版本身就可能存在问题，api不是为开发版打造的。
