### ISSUE TITLE
使用 unidbg-fetch-qsign 后无法正常登入

### ISSUE THREAD

**Issue by Arispex** [DreamVoid/MiraiMC#443]
### 问题描述

使用 unidbg-fetch-qsign 后无法正常登入，也尝试过[临时办法](https://github.com/DreamVoid/MiraiMC/discussions/440#discussioncomment-6676847)，出现了新的问题（见日志）

### 复现方法

1. 正确安装插件并启动服务端
2. 启用 `bot.register-encrypt-service` 后重启服务端
3. 修改 `services.json`
4. 使用 `/mirai login` 登入 QQ

### 服务端类型

Bukkit

### 服务端版本

Paper-1.20.1

### MiraiMC 插件版本

1.8

### 服务端日志

```text
使用 unidbg-fetch-qsign 后无法正常登入的服务端完整日志：https://mclo.gs/i4fyv9r
使用临时办法后的完整日志：https://mclo.gs/4e4NHvp
```

### 额外说明

系统：MacOS 13
Java版本：17

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和 [issue 列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。
- [ ] 我确认我没有看这些选择框就随便勾选了。
- [X] 我明白，如果没有正确填写 issue 模板的内容，本 issue 将会直接被关闭并被锁定。
- [X] 我明白，如果滥用 issue 功能，我将会被列入黑名单。

**Comment by DreamVoid** [comment]
使用了Folia导致的，建议用正常服务端

**Comment by DreamVoid** [comment]
临时修复方案，添加参数`-DMiraiMC.EncryptService.REQUEST_TOKEN_INTERVAL=0`
