### ISSUE TITLE
Mohist 1.7.10端无法登陆（添加HttpApi支持）

### ISSUE THREAD

**Issue by xiaovoaix** [DreamVoid/MiraiMC#46]
**问题描述**

使用文档中推荐的Mohist1.7.10端测试时
输入mirai login xxxxx xxxxx后无反应
过一段时间后输入mirai list会显示：xxxxx-离线

**复现方法**

就只有一个Mohist端和miraimc插件

**版本类型**

* Minecraft 服务端版本：Mohist 1.7.10-40
* MiraiMC 插件版本：1.5

**截图**

![TLORDSIE6FVF3Z%X({RABQH](https://user-images.githubusercontent.com/58628662/135402551-8f0b3dda-00f4-41f6-9c52-f6c92ab52df3.png)
**服务器日志**

```
啥也没有orz
```

**额外说明**

无

**Comment by xiaovoaix** [comment]
只能说，麻了（
看来1.7.10不配用机器人QAQ

**Comment by xiaovoaix** [comment]
顺便一提，Mohist 1.7.10根目录下也有“cauldron.yml”（

**Comment by DreamVoid** [comment]
不管有没有报错，都提供完整的服务器日志

**Comment by xiaovoaix** [comment]
[latest.log](https://github.com/DreamVoid/MiraiMC/files/7258901/latest.log)

**Comment by xiaovoaix** [comment]
[fml-server-latest.log](https://github.com/DreamVoid/MiraiMC/files/7258909/fml-server-latest.log)

**Comment by xiaovoaix** [comment]
ok了

**Comment by DreamVoid** [comment]
```[21:22:41 INFO]: Reload not allowed on a Cauldron server.```
那没事了

**Comment by DreamVoid** [comment]
https://wiki.miraimc.dreamvoid.ml/troubleshoot/compatibility-report/cauldron#howtosolve

**Comment by xiaovoaix** [comment]
麻了
希望1.6的时候能用吧

**Comment by xiaovoaix** [comment]
瞧瞧我发现了什么，reopen（）

**Comment by DreamVoid** [comment]
现在压力来到了最后阶段——HTTP API

**Comment by DreamVoid** [comment]
这搞得我不想维护了，HTTP API 太困难了，还是core来的方便。我看也不会有什么人用吧。

**Comment by xiaovoaix** [comment]
噔噔咚（

**Comment by xiaovoaix** [comment]
1.7没有别的同时支持插件和mod的端了貌似

**Comment by MC-Nirvana** [comment]
经过测试，截至mohist 1.20.1目前能下载到的最新构建上依旧存在问题（插件能成功加载，但是配合其[MiraiMCAddon-Overflow](https://github.com/DreamVoid/MiraiMCAddon-Overflow)扩展插件后无法正常链接OneBot机器人）

**Comment by MC-Nirvana** [comment]
并且重载该插件的时候会报错，估计是因为不支持MiraiMC不支持Mohist 1.20.1导致的（因为Paper1.21下没事，但paper1.20.1下连加载都无法加载）

**Comment by MC-Nirvana** [comment]
好吧，测试了之后是[MiraiMCAddon-Overflow](https://github.com/DreamVoid/MiraiMCAddon-Overflow)这个扩展新版本的问题，不支持1.20.1。我降了一个版本后正常使用，MiraiMC也能正常读取到机器人
