### ISSUE TITLE
添加外部核心支持以实现对接如Overflow的修改核心

### ISSUE THREAD

**Issue by zzzyyylllty** [DreamVoid/MiraiMC#510]
### 功能描述

MiraiMC内嵌使用Mirai核心，
导致其无法对接如Overflow这类通过替换mirai-core来实现对接到Onebot的修改核心。
希望添加使用外部核心的配置选项。

### 使用方法

1. 添加使用外部核心选项
2. 启动时检测选项，使用外部核心的方法

### 协议

- [X] 我已查阅 [issue 列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。
- [ ] 我确认我没有看这些选择框就随便勾选了。
- [X] 我明白，如果没有正确填写 issue 模板的内容，本 issue 将会直接被关闭并被锁定。
- [X] 我明白，如果滥用 issue 功能，我将会被列入黑名单。

**Comment by DreamVoid** [comment]
请提供 Overflow 的介绍链接

**Comment by zzzyyylllty** [comment]
https://github.com/MrXiaoM/overflow







                       
原始邮件
                       
                     

发件人："流光"< ***@***.*** &gt;;

发件时间：2024/5/20 23:26

收件人："DreamVoid/MiraiMC"< ***@***.*** &gt;;

抄送人："zzzyyylllty"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [DreamVoid/MiraiMC] 添加外部核心支持以实现对接如Overflow的修改核心 (Issue #510)




 
请提供 Overflow 的介绍链接

**Comment by DreamVoid** [comment]
1.8将会以附属插件的形式添加支持

**Comment by DreamVoid** [comment]
https://github.com/DreamVoid/MiraiMCAddon-Overflow/releases/tag/v1.0

先行版

**Comment by DreamVoid** [comment]
实验成功

![image](https://github.com/DreamVoid/MiraiMC/assets/45266046/ea146843-d1a8-47e1-8ab9-6955805defd8)

![image](https://github.com/DreamVoid/MiraiMC/assets/45266046/a93cef40-8d1a-4125-979f-8a959772b1b8)

**Comment by TUCAOEVER** [comment]
Mirai基本上终结了，很多开发者转向Overflow一类NT修改核心，是否可以直接合并插件？

**Comment by DreamVoid** [comment]
> Mirai基本上终结了，很多开发者转向Overflow一类NT修改核心，是否可以直接合并插件？

有在考虑，但这类需要依赖第三方软件的使用方式在不同平台和系统有不同使用方案，比如一个QQ是一个连接地址，另一个QQ又是另一个连接地址，目前还是先这样使用。

**Comment by Q2297045667** [comment]
> > Mirai基本上终结了，很多开发者转向Overflow一类NT修改核心，是否可以直接合并插件？
> 
> 有在考虑，但这类需要依赖第三方软件的使用方式在不同平台和系统有不同使用方案，比如一个QQ是一个连接地址，另一个QQ又是另一个连接地址，目前还是先这样使用。

可以参考一下https://github.com/NapNeko/NapCatQQ
这个实现了多种链接方式，我这边对接Koishi平台很好用
