### ISSUE TITLE
无法进入验证页面

### ISSUE THREAD

**Issue by notwhitebear** [DreamVoid/MiraiMC#520]
### 问题描述

*配置未修改，版本1.8.3。在进行验证的时候进入控制台提示的链接，跳出“404 Not Found nginx/1.19.9”

### 复现方法

1. 进行一次需要图形验证的QQ号绑定

### 服务端类型

Bukkit

### 服务端版本

leaves-1.20.6

### MiraiMC 插件版本

1.8.3

### 服务端日志

```text
https://mclo.gs/WCnqyEX
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和 [issue 列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。
- [ ] 我确认我没有看这些选择框就随便勾选了。
- [X] 我明白，如果没有正确填写 issue 模板的内容，本 issue 将会直接被关闭并被锁定。
- [X] 我明白，如果滥用 issue 功能，我将会被列入黑名单。

**Comment by DreamVoid** [comment]
自行检查链接是否复制完全，我刚刚测试了你的服务器日志的所有链接，均可以正常进入验证码页面。
