### ISSUE TITLE
请问可以让sendMessage支持MusicShare吗(mirai下的Message)

### ISSUE THREAD

**Issue by killerprojecte** [DreamVoid/MiraiMC#57]
**功能描述**

支持发送MusicShare(非Mirai码)

**使用方法**

1. 用于让我开发的FlyMusic能够支持MiraiMC

**额外说明**

**Comment by DreamVoid** [comment]
MusicKind是什么，有相关链接或者文档吗

**Comment by killerprojecte** [comment]
相关代码
https://github.com/mamoe/mirai/blob/dev/mirai-core-api/src/commonMain/kotlin/message/data/MusicShare.kt
mirai文档
https://docs.mirai.mamoe.net/Messages.html#%E6%B6%88%E6%81%AF%E5%85%83%E7%B4%A0

**Comment by DreamVoid** [comment]
目前 1.6 版本需要更新的东西有点多，**可能**会在 1.6 版本加入。

**Comment by killerprojecte** [comment]
好的 非常感谢您的支持 在1.6版本更新后我会第一时间对我所开发的插件增加与MiraiMC的支持

**Comment by DreamVoid** [comment]
#48

**Comment by DreamVoid** [comment]
Commit https://github.com/DreamVoid/MiraiMC/commit/f57458928deb655042ade0c13c8e51278c626b44 已增加相关方法，待发布到Maven中央仓库后可使用。
