### ISSUE TITLE
Paper 1.18问题

### ISSUE THREAD

**Issue by Shizuri23** [DreamVoid/MiraiMC#58]
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/46082179/145494076-a30e3222-c689-4554-9afd-00a442680775.png">
之后插件就像不能使用，只能重启服务器
QQ设备锁之类的都是关闭的

**Comment by DreamVoid** [comment]
那么就打开设备锁。
另外请始终使用最新版本，即使登录失败也不会造成插件无法使用的问题。
