### ISSUE TITLE
发送消息命令不支持空格与换行符

### ISSUE THREAD

**Issue by Cnzw** [DreamVoid/MiraiMC#60]
**问题描述**

sendgroupmessage和sendfriendnudge不支持空格和换行符

**复现方法**

1. /mirai sendgroupmessage 123 123 **测试1\n测试2 测试3**
2. 群内只收到"**测试1\n测试2**"(换行符未转换, 空格后内容丢失)

**版本类型**

* Minecraft 服务端版本：Paper-1.12.2
* MiraiMC 插件版本：1.5.1

**截图**

null

**服务器日志**

```
null
```

**额外说明**

null

**Comment by DreamVoid** [comment]
1.5.2 即将修复此问题，感谢你的反馈。
