### ISSUE TITLE
事件

### ISSUE THREAD

**Issue by kzheart** [DreamVoid/MiraiMC#7]
v1.1 里面与消息，好友，机器人有关的事件没有直接获取到Mirai core提供的 Friend对象和bot对象 只能获取到相应的QQ号，。 是打算在后面 在api里面再造一些 api用的Friend类或者Bot类吗...

**Comment by DreamVoid** [comment]
是的，就像调用Minecraft不需要调用net.minecraft.server而调用org.bukkit一样。
我想让MiraiMC提供的API能直接实现各种功能而不需要依赖内部库，因为后续我会减小插件体积，将调用mirai core改为调用外部jar而不集成到插件本体，这样也可以方便更新mirai
如果你现在有相关需求的话，可以直接调用```getBot```，然后实现你想实现的功能
