### ISSUE TITLE
Int值过与小了

### ISSUE THREAD

**Issue by isYyc** [DreamVoid/MiraiMC#8]
我是一名开发者，在使用你的MiraiMC时发现了一些登陆上的问题。
我的机器人QQ为：3550706134 在登陆时，你的插件报错。

报错内容：
java.lang.NumberFormatException: For input string: "3550706134"

翻看了一下MiraiMC的源码发现时/mirai login部分的代码写的有问题

代码如下：（me.dreamvoid.miraimc.bukkit.CommandHandler的第146行）
CommandHandler.this.mirai.doBotLogin((long)Integer.parseInt(args[1]), args[2], Protocol);

这里将命令里的第一个args[1](int) 强转为long。但是int值太小了，希望作者可以改一下这个问题。

一开始手滑打错打成long值过小233333（丢人

**Comment by DreamVoid** [comment]
你的系统版本是？

**Comment by isYyc** [comment]
> 你的系统版本是？

MacOS BigSur11

**Comment by isYyc** [comment]
> > > 你的系统版本是？
> > 
> > 
> > MacOS BigSur11
> 
> 没有相关设备和系统，无法复现。
> 请在Linux或Windows环境下尝试有无此问题。

好的 我用linux试试看

**Comment by isYyc** [comment]
![image](https://user-images.githubusercontent.com/87295582/125242613-86345500-e31f-11eb-8d45-f8195e791fee.png)
centos7 下测试也存在这个问题

**Comment by isYyc** [comment]
int的取值范围最大是 2147483648 但是我机器人的qqid是3550706134
虽然我不太理解为什么args1要加一个intger.parseint然后再转long

**Comment by DreamVoid** [comment]
多次使用CentOS 7、Ubuntu 20.04均没有出现此问题，请尝试使用此版本的MiraiMC尝试复现：https://1drv.ms/u/s!AkLwq1d_tN71wQbTXqvBMNAI28IO?e=M8Sdjc

**Comment by DreamVoid** [comment]
长时间未得到回复，将暂做归档处理
