### ISSUE TITLE
无法加载插件

### ISSUE THREAD

**Issue by Thelongyu** [DreamVoid/MiraiMC#82]
问题描述

疯狂刷新代码

复现方法
1. 服务器开启到半的时候就疯狂提示

版本类型

* Minecraft 服务端版本：spigot-3.21.0.1
* MiraiMC 插件版本：1.5.3

截图

![QQ截图20220122132618](https://user-images.githubusercontent.com/95472664/150626177-2f319cd1-9128-4014-b3d4-d07e67a757e6.png)

服务器日志

[latest.log](https://github.com/DreamVoid/MiraiMC/files/7917691/latest.log)

额外说明

无

**Comment by Thelongyu** [comment]
配置我重新删除还是这样

**Comment by Thelongyu** [comment]
![QQ截图20220122133449](https://user-images.githubusercontent.com/95472664/150626315-96a84d0f-92c9-496d-aa69-d5038ca6af8e.png)从这一行开始就出去问题了

**Comment by DreamVoid** [comment]
请检查服务器网络能否正常连接到腾讯服务器。
如无效，尝试在配置文件中设置 mirai 核心版本为2.8.2。

**Comment by Thelongyu** [comment]
谢谢
